FROM ubuntu:latest

RUN apt-get update && \
    apt-get install sudo -y && \
    sudo apt-get install build-essential -y && sudo apt-get install libc6-dev -y && sudo apt-get install git -y && sudo apt-get install golang -y

RUN go install github.com/goreleaser/goreleaser@latest

RUN mkdir -p /go/src/github.com/mitchellh && \
    cd /go/src/github.com/mitchellh && \
    git clone https://github.com/mitchellh/golicense.git && \
    cd golicense && \
    git checkout v0.2.0 && \
    go install . && \
    mkdir -p /go/src/github.com/confluentinc/cli && \
    cd /go/src/github.com/confluentinc/cli

RUN export GOPATH=$HOME/go && \
    export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

COPY . /go/src/github.com/confluentinc/cli/

COPY .netrc /root/.netrc
RUN chmod 600 /root/.netrc

RUN cd /go/src/github.com/confluentinc/cli && \
    make gorelease-ubuntu ; \
    for file in dist/*linux*; do mv -v "$file" "${file/linux/ubuntu}"; done ; \
    for file in dist/*.txt; do mv -v "$file" "${file/checksums/checksums_ubuntu}"; done; \
    for file in dist/*.txt; do sed -i 's/linux/ubuntu/g' $file ; done
 

