steps:
  - task: DownloadSecureFile@1
    name: idrsa
    displayName: 'Securely download id_rsa from Azure vault'
    inputs:
      secureFile: 'id_rsa'
  
  - task: DownloadSecureFile@1
    name: netrc
    displayName: 'Securely download netrc from Azure vault'
    inputs:
      secureFile: 'netrc'
  
- script: |
    echo '##vso[task.prependpath]$(GOROOT)\bin'
    echo '##vso[task.prependpath]$(GOPATH)\bin'
    echo '##vso[task.setvariable variable=PATH;]$(GOROOT)\bin;$(GOPATH)\bin;$(PATH)'
    echo '$(GOROOT)'
    echo '$(GOPATH)'
    echo '$(PATH)'
    echo '%PATH%'
    mkdir ${GOPATH}\bin
    mkdir ${GOROOT}\bin
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Set up the Go workspace (Windows)'

- script: |
    mv $(netrc.secureFilePath) ~/.netrc
    mkdir ~/.ssh
    sudo mv $(idrsa.secureFilePath) ~/.ssh/
    sudo chmod 400 ~/.ssh/id_rsa
  condition: ne( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Put secrets in their right places (non-Windows)'
