// Code generated by cli-terraform-generator; DO NOT EDIT.

package test

func (s *CLITestSuite) TestEndpointEndpointList() {
	tests := []CLITest{
		{args: "endpoint endpoint list --service KAFKA", fixture: "endpoint/endpoint/list.golden"},
		{args: "endpoint endpoint list --service KAFKA --region us-west-2", fixture: "endpoint/endpoint/list-region.golden"},
		{args: "endpoint endpoint list --service KAFKA --is-private", fixture: "endpoint/endpoint/list-is-private.golden"},
		{args: "endpoint endpoint list --service KAFKA --resource lkc-abc123", fixture: "endpoint/endpoint/list-resource.golden"},
		{args: "endpoint endpoint list --service KAFKA -o json", fixture: "endpoint/endpoint/list-json.golden"},
		{args: "endpoint endpoint list --service KAFKA -o yaml", fixture: "endpoint/endpoint/list-yaml.golden"},
	}

	for _, test := range tests {
		test.login = "cloud"
		s.runIntegrationTest(test)
	}
}
