// Code generated by cli-terraform-generator v0.8.4; DO NOT EDIT.

package test

func (s *CLITestSuite) TestNotificationsResourceSubscriptionCreate() {
	tests := []CLITest{
		{args: "notifications resource-subscription create --integrations val1,val2 --notification-type notification-type-value --resource environment=env-456xy/cloud-cluster=lkc-df123/connector=my_datagen_connector --resource-type environment", fixture: "notifications/resource-subscription/create/create.golden"},
		{args: "notifications resource-subscription create --integrations val1,val2 --notification-type notification-type-value --resource environment=env-456xy/cloud-cluster=lkc-df123/connector=my_datagen_connector --resource-type environment --current-state enabled", fixture: "notifications/resource-subscription/create/create-current-state.golden"},
	}

	for _, test := range tests {
		test.login = "cloud"
		s.runIntegrationTest(test)
	}
}

func (s *CLITestSuite) TestNotificationsResourceSubscriptionDelete() {
	tests := []CLITest{
		{args: "notifications resource-subscription delete resource-subscription-1 --force", fixture: "notifications/resource-subscription/delete/delete.golden"},
		{args: "notifications resource-subscription delete resource-subscription-1", input: "y\n", fixture: "notifications/resource-subscription/delete/delete-no-force.golden"},
		{args: "notifications resource-subscription delete resource-subscription-1 resource-subscription-2", input: "y\n", fixture: "notifications/resource-subscription/delete/delete-multiple.golden"},
		{args: "notifications resource-subscription delete invalid", fixture: "notifications/resource-subscription/delete/delete-invalid.golden", exitCode: 1},
	}

	for _, test := range tests {
		test.login = "cloud"
		s.runIntegrationTest(test)
	}
}

func (s *CLITestSuite) TestNotificationsResourceSubscriptionDescribe() {
	tests := []CLITest{
		{args: "notifications resource-subscription describe resource-subscription-1", fixture: "notifications/resource-subscription/describe/describe.golden"},
		{args: "notifications resource-subscription describe resource-subscription-1 -o json", fixture: "notifications/resource-subscription/describe/describe-json.golden"},
		{args: "notifications resource-subscription describe resource-subscription-1 -o yaml", fixture: "notifications/resource-subscription/describe/describe-yaml.golden"},
		{args: "notifications resource-subscription describe invalid", fixture: "notifications/resource-subscription/describe/describe-invalid.golden", exitCode: 1},
	}

	for _, test := range tests {
		test.login = "cloud"
		s.runIntegrationTest(test)
	}
}

func (s *CLITestSuite) TestNotificationsResourceSubscriptionUpdate() {
	tests := []CLITest{
		{args: "notifications resource-subscription update resource-subscription-1 --resource environment=env-456xy/cloud-cluster=lkc-df123/connector=my_datagen_connector", fixture: "notifications/resource-subscription/update/update-resource.golden"},
		{args: "notifications resource-subscription update resource-subscription-1 --resource-type environment", fixture: "notifications/resource-subscription/update/update-resource-type.golden"},
		{args: "notifications resource-subscription update resource-subscription-1 --current-state enabled", fixture: "notifications/resource-subscription/update/update-current-state.golden"},
		{args: "notifications resource-subscription update resource-subscription-1 --integrations val1,val2", fixture: "notifications/resource-subscription/update/update-integrations.golden"},
		{args: "notifications resource-subscription update invalid", fixture: "notifications/resource-subscription/update/update-invalid.golden", exitCode: 1},
	}

	for _, test := range tests {
		test.login = "cloud"
		s.runIntegrationTest(test)
	}
}
