// Code generated by cli-terraform-generator v0.8.1; DO NOT EDIT.

package test

func (s *CLITestSuite) TestUsmKafkaClusterCreate() {
	tests := []CLITest{
		{args: "usm kafka-cluster register test-name --cloud aws --name My-Prod-CP-Cluster --region us-east-1", fixture: "usm/kafka-cluster/create/create.golden"},
	}

	for _, test := range tests {
		test.login = "cloud"
		s.runIntegrationTest(test)
	}
}

func (s *CLITestSuite) TestUsmKafkaClusterDelete() {
	tests := []CLITest{
		{args: "usm kafka-cluster deregister usmkc-1 --force", fixture: "usm/kafka-cluster/delete/delete.golden"},
		{args: "usm kafka-cluster deregister usmkc-1", input: "y\n", fixture: "usm/kafka-cluster/delete/delete-no-force.golden"},
		{args: "usm kafka-cluster deregister usmkc-1 usmkc-2", input: "y\n", fixture: "usm/kafka-cluster/delete/delete-multiple.golden"},
		{args: "usm kafka-cluster deregister invalid", fixture: "usm/kafka-cluster/delete/delete-invalid.golden", exitCode: 1},
	}

	for _, test := range tests {
		test.login = "cloud"
		s.runIntegrationTest(test)
	}
}

func (s *CLITestSuite) TestUsmKafkaClusterDescribe() {
	tests := []CLITest{
		{args: "usm kafka-cluster describe usmkc-1", fixture: "usm/kafka-cluster/describe/describe.golden"},
		{args: "usm kafka-cluster describe usmkc-1 -o json", fixture: "usm/kafka-cluster/describe/describe-json.golden"},
		{args: "usm kafka-cluster describe usmkc-1 -o yaml", fixture: "usm/kafka-cluster/describe/describe-yaml.golden"},
		{args: "usm kafka-cluster describe invalid", fixture: "usm/kafka-cluster/describe/describe-invalid.golden", exitCode: 1},
	}

	for _, test := range tests {
		test.login = "cloud"
		s.runIntegrationTest(test)
	}
}

func (s *CLITestSuite) TestUsmKafkaClusterList() {
	tests := []CLITest{
		{args: "usm kafka-cluster list", fixture: "usm/kafka-cluster/list/list.golden"},
		{args: "usm kafka-cluster list -o json", fixture: "usm/kafka-cluster/list/list-json.golden"},
		{args: "usm kafka-cluster list -o yaml", fixture: "usm/kafka-cluster/list/list-yaml.golden"},
	}

	for _, test := range tests {
		test.login = "cloud"
		s.runIntegrationTest(test)
	}
}

func (s *CLITestSuite) TestUsmKafkaCluster_Autocomplete() {
	tests := []CLITest{
		{args: "__complete usm kafka-cluster deregister \"\"", fixture: "usm/kafka-cluster/delete/delete-autocomplete.golden"},
		{args: "__complete usm kafka-cluster describe \"\"", fixture: "usm/kafka-cluster/describe/describe-autocomplete.golden"},
	}

	for _, test := range tests {
		test.login = "cloud"
		s.runIntegrationTest(test)
	}
}
