// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/confluentinc/cli/v4/pkg/auth (interfaces: AuthTokenHandler)
//
// Generated by this command:
//
//	mockgen -typed -destination=../../mock/auth_token_handler.go -package=mock github.com/confluentinc/cli/v4/pkg/auth AuthTokenHandler
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	auth "github.com/confluentinc/cli/v4/pkg/auth"
	mdsv1 "github.com/confluentinc/mds-sdk-go-public/mdsv1"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthTokenHandler is a mock of AuthTokenHandler interface.
type MockAuthTokenHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAuthTokenHandlerMockRecorder
	isgomock struct{}
}

// MockAuthTokenHandlerMockRecorder is the mock recorder for MockAuthTokenHandler.
type MockAuthTokenHandlerMockRecorder struct {
	mock *MockAuthTokenHandler
}

// NewMockAuthTokenHandler creates a new mock instance.
func NewMockAuthTokenHandler(ctrl *gomock.Controller) *MockAuthTokenHandler {
	mock := &MockAuthTokenHandler{ctrl: ctrl}
	mock.recorder = &MockAuthTokenHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthTokenHandler) EXPECT() *MockAuthTokenHandlerMockRecorder {
	return m.recorder
}

// GetCCloudTokens mocks base method.
func (m *MockAuthTokenHandler) GetCCloudTokens(arg0 auth.CCloudClientFactory, arg1 string, arg2 *auth.Credentials, arg3 bool, arg4 string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCCloudTokens", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCCloudTokens indicates an expected call of GetCCloudTokens.
func (mr *MockAuthTokenHandlerMockRecorder) GetCCloudTokens(arg0, arg1, arg2, arg3, arg4 any) *MockAuthTokenHandlerGetCCloudTokensCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCCloudTokens", reflect.TypeOf((*MockAuthTokenHandler)(nil).GetCCloudTokens), arg0, arg1, arg2, arg3, arg4)
	return &MockAuthTokenHandlerGetCCloudTokensCall{Call: call}
}

// MockAuthTokenHandlerGetCCloudTokensCall wrap *gomock.Call
type MockAuthTokenHandlerGetCCloudTokensCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthTokenHandlerGetCCloudTokensCall) Return(arg0, arg1 string, arg2 error) *MockAuthTokenHandlerGetCCloudTokensCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthTokenHandlerGetCCloudTokensCall) Do(f func(auth.CCloudClientFactory, string, *auth.Credentials, bool, string) (string, string, error)) *MockAuthTokenHandlerGetCCloudTokensCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthTokenHandlerGetCCloudTokensCall) DoAndReturn(f func(auth.CCloudClientFactory, string, *auth.Credentials, bool, string) (string, string, error)) *MockAuthTokenHandlerGetCCloudTokensCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetConfluentToken mocks base method.
func (m *MockAuthTokenHandler) GetConfluentToken(arg0 *mdsv1.APIClient, arg1 *auth.Credentials, arg2 bool) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfluentToken", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetConfluentToken indicates an expected call of GetConfluentToken.
func (mr *MockAuthTokenHandlerMockRecorder) GetConfluentToken(arg0, arg1, arg2 any) *MockAuthTokenHandlerGetConfluentTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfluentToken", reflect.TypeOf((*MockAuthTokenHandler)(nil).GetConfluentToken), arg0, arg1, arg2)
	return &MockAuthTokenHandlerGetConfluentTokenCall{Call: call}
}

// MockAuthTokenHandlerGetConfluentTokenCall wrap *gomock.Call
type MockAuthTokenHandlerGetConfluentTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthTokenHandlerGetConfluentTokenCall) Return(arg0, arg1 string, arg2 error) *MockAuthTokenHandlerGetConfluentTokenCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthTokenHandlerGetConfluentTokenCall) Do(f func(*mdsv1.APIClient, *auth.Credentials, bool) (string, string, error)) *MockAuthTokenHandlerGetConfluentTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthTokenHandlerGetConfluentTokenCall) DoAndReturn(f func(*mdsv1.APIClient, *auth.Credentials, bool) (string, string, error)) *MockAuthTokenHandlerGetConfluentTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
