// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/confluentinc/cli/v4/pkg/local (interfaces: ConfluentHome)
//
// Generated by this command:
//
//	mockgen -typed -destination=../../mock/confluent_home.go -package=mock github.com/confluentinc/cli/v4/pkg/local ConfluentHome
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConfluentHome is a mock of ConfluentHome interface.
type MockConfluentHome struct {
	ctrl     *gomock.Controller
	recorder *MockConfluentHomeMockRecorder
	isgomock struct{}
}

// MockConfluentHomeMockRecorder is the mock recorder for MockConfluentHome.
type MockConfluentHomeMockRecorder struct {
	mock *MockConfluentHome
}

// NewMockConfluentHome creates a new mock instance.
func NewMockConfluentHome(ctrl *gomock.Controller) *MockConfluentHome {
	mock := &MockConfluentHome{ctrl: ctrl}
	mock.recorder = &MockConfluentHomeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfluentHome) EXPECT() *MockConfluentHomeMockRecorder {
	return m.recorder
}

// FindFile mocks base method.
func (m *MockConfluentHome) FindFile(pattern string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFile", pattern)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFile indicates an expected call of FindFile.
func (mr *MockConfluentHomeMockRecorder) FindFile(pattern any) *MockConfluentHomeFindFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFile", reflect.TypeOf((*MockConfluentHome)(nil).FindFile), pattern)
	return &MockConfluentHomeFindFileCall{Call: call}
}

// MockConfluentHomeFindFileCall wrap *gomock.Call
type MockConfluentHomeFindFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfluentHomeFindFileCall) Return(arg0 []string, arg1 error) *MockConfluentHomeFindFileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfluentHomeFindFileCall) Do(f func(string) ([]string, error)) *MockConfluentHomeFindFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfluentHomeFindFileCall) DoAndReturn(f func(string) ([]string, error)) *MockConfluentHomeFindFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetConfluentVersion mocks base method.
func (m *MockConfluentHome) GetConfluentVersion() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfluentVersion")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfluentVersion indicates an expected call of GetConfluentVersion.
func (mr *MockConfluentHomeMockRecorder) GetConfluentVersion() *MockConfluentHomeGetConfluentVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfluentVersion", reflect.TypeOf((*MockConfluentHome)(nil).GetConfluentVersion))
	return &MockConfluentHomeGetConfluentVersionCall{Call: call}
}

// MockConfluentHomeGetConfluentVersionCall wrap *gomock.Call
type MockConfluentHomeGetConfluentVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfluentHomeGetConfluentVersionCall) Return(arg0 string, arg1 error) *MockConfluentHomeGetConfluentVersionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfluentHomeGetConfluentVersionCall) Do(f func() (string, error)) *MockConfluentHomeGetConfluentVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfluentHomeGetConfluentVersionCall) DoAndReturn(f func() (string, error)) *MockConfluentHomeGetConfluentVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetConnectorConfigFile mocks base method.
func (m *MockConfluentHome) GetConnectorConfigFile(connector string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectorConfigFile", connector)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectorConfigFile indicates an expected call of GetConnectorConfigFile.
func (mr *MockConfluentHomeMockRecorder) GetConnectorConfigFile(connector any) *MockConfluentHomeGetConnectorConfigFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectorConfigFile", reflect.TypeOf((*MockConfluentHome)(nil).GetConnectorConfigFile), connector)
	return &MockConfluentHomeGetConnectorConfigFileCall{Call: call}
}

// MockConfluentHomeGetConnectorConfigFileCall wrap *gomock.Call
type MockConfluentHomeGetConnectorConfigFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfluentHomeGetConnectorConfigFileCall) Return(arg0 string, arg1 error) *MockConfluentHomeGetConnectorConfigFileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfluentHomeGetConnectorConfigFileCall) Do(f func(string) (string, error)) *MockConfluentHomeGetConnectorConfigFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfluentHomeGetConnectorConfigFileCall) DoAndReturn(f func(string) (string, error)) *MockConfluentHomeGetConnectorConfigFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetFile mocks base method.
func (m *MockConfluentHome) GetFile(path ...string) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range path {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFile", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockConfluentHomeMockRecorder) GetFile(path ...any) *MockConfluentHomeGetFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockConfluentHome)(nil).GetFile), path...)
	return &MockConfluentHomeGetFileCall{Call: call}
}

// MockConfluentHomeGetFileCall wrap *gomock.Call
type MockConfluentHomeGetFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfluentHomeGetFileCall) Return(arg0 string, arg1 error) *MockConfluentHomeGetFileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfluentHomeGetFileCall) Do(f func(...string) (string, error)) *MockConfluentHomeGetFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfluentHomeGetFileCall) DoAndReturn(f func(...string) (string, error)) *MockConfluentHomeGetFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetKafkaScript mocks base method.
func (m *MockConfluentHome) GetKafkaScript(mode, format string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKafkaScript", mode, format)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKafkaScript indicates an expected call of GetKafkaScript.
func (mr *MockConfluentHomeMockRecorder) GetKafkaScript(mode, format any) *MockConfluentHomeGetKafkaScriptCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKafkaScript", reflect.TypeOf((*MockConfluentHome)(nil).GetKafkaScript), mode, format)
	return &MockConfluentHomeGetKafkaScriptCall{Call: call}
}

// MockConfluentHomeGetKafkaScriptCall wrap *gomock.Call
type MockConfluentHomeGetKafkaScriptCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfluentHomeGetKafkaScriptCall) Return(arg0 string, arg1 error) *MockConfluentHomeGetKafkaScriptCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfluentHomeGetKafkaScriptCall) Do(f func(string, string) (string, error)) *MockConfluentHomeGetKafkaScriptCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfluentHomeGetKafkaScriptCall) DoAndReturn(f func(string, string) (string, error)) *MockConfluentHomeGetKafkaScriptCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetServiceScript mocks base method.
func (m *MockConfluentHome) GetServiceScript(action, service string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceScript", action, service)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceScript indicates an expected call of GetServiceScript.
func (mr *MockConfluentHomeMockRecorder) GetServiceScript(action, service any) *MockConfluentHomeGetServiceScriptCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceScript", reflect.TypeOf((*MockConfluentHome)(nil).GetServiceScript), action, service)
	return &MockConfluentHomeGetServiceScriptCall{Call: call}
}

// MockConfluentHomeGetServiceScriptCall wrap *gomock.Call
type MockConfluentHomeGetServiceScriptCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfluentHomeGetServiceScriptCall) Return(arg0 string, arg1 error) *MockConfluentHomeGetServiceScriptCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfluentHomeGetServiceScriptCall) Do(f func(string, string) (string, error)) *MockConfluentHomeGetServiceScriptCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfluentHomeGetServiceScriptCall) DoAndReturn(f func(string, string) (string, error)) *MockConfluentHomeGetServiceScriptCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetVersion mocks base method.
func (m *MockConfluentHome) GetVersion(service string, zookeeperMode bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", service, zookeeperMode)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockConfluentHomeMockRecorder) GetVersion(service, zookeeperMode any) *MockConfluentHomeGetVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockConfluentHome)(nil).GetVersion), service, zookeeperMode)
	return &MockConfluentHomeGetVersionCall{Call: call}
}

// MockConfluentHomeGetVersionCall wrap *gomock.Call
type MockConfluentHomeGetVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfluentHomeGetVersionCall) Return(arg0 string, arg1 error) *MockConfluentHomeGetVersionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfluentHomeGetVersionCall) Do(f func(string, bool) (string, error)) *MockConfluentHomeGetVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfluentHomeGetVersionCall) DoAndReturn(f func(string, bool) (string, error)) *MockConfluentHomeGetVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HasFile mocks base method.
func (m *MockConfluentHome) HasFile(path ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range path {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HasFile", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasFile indicates an expected call of HasFile.
func (mr *MockConfluentHomeMockRecorder) HasFile(path ...any) *MockConfluentHomeHasFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasFile", reflect.TypeOf((*MockConfluentHome)(nil).HasFile), path...)
	return &MockConfluentHomeHasFileCall{Call: call}
}

// MockConfluentHomeHasFileCall wrap *gomock.Call
type MockConfluentHomeHasFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfluentHomeHasFileCall) Return(arg0 bool, arg1 error) *MockConfluentHomeHasFileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfluentHomeHasFileCall) Do(f func(...string) (bool, error)) *MockConfluentHomeHasFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfluentHomeHasFileCall) DoAndReturn(f func(...string) (bool, error)) *MockConfluentHomeHasFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsAtLeastVersion mocks base method.
func (m *MockConfluentHome) IsAtLeastVersion(targetVersion string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAtLeastVersion", targetVersion)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAtLeastVersion indicates an expected call of IsAtLeastVersion.
func (mr *MockConfluentHomeMockRecorder) IsAtLeastVersion(targetVersion any) *MockConfluentHomeIsAtLeastVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAtLeastVersion", reflect.TypeOf((*MockConfluentHome)(nil).IsAtLeastVersion), targetVersion)
	return &MockConfluentHomeIsAtLeastVersionCall{Call: call}
}

// MockConfluentHomeIsAtLeastVersionCall wrap *gomock.Call
type MockConfluentHomeIsAtLeastVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfluentHomeIsAtLeastVersionCall) Return(arg0 bool, arg1 error) *MockConfluentHomeIsAtLeastVersionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfluentHomeIsAtLeastVersionCall) Do(f func(string) (bool, error)) *MockConfluentHomeIsAtLeastVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfluentHomeIsAtLeastVersionCall) DoAndReturn(f func(string) (bool, error)) *MockConfluentHomeIsAtLeastVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsConfluentPlatform mocks base method.
func (m *MockConfluentHome) IsConfluentPlatform() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConfluentPlatform")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsConfluentPlatform indicates an expected call of IsConfluentPlatform.
func (mr *MockConfluentHomeMockRecorder) IsConfluentPlatform() *MockConfluentHomeIsConfluentPlatformCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConfluentPlatform", reflect.TypeOf((*MockConfluentHome)(nil).IsConfluentPlatform))
	return &MockConfluentHomeIsConfluentPlatformCall{Call: call}
}

// MockConfluentHomeIsConfluentPlatformCall wrap *gomock.Call
type MockConfluentHomeIsConfluentPlatformCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfluentHomeIsConfluentPlatformCall) Return(arg0 bool, arg1 error) *MockConfluentHomeIsConfluentPlatformCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfluentHomeIsConfluentPlatformCall) Do(f func() (bool, error)) *MockConfluentHomeIsConfluentPlatformCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfluentHomeIsConfluentPlatformCall) DoAndReturn(f func() (bool, error)) *MockConfluentHomeIsConfluentPlatformCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadServiceConfig mocks base method.
func (m *MockConfluentHome) ReadServiceConfig(service string, zookeeperMode bool) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadServiceConfig", service, zookeeperMode)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadServiceConfig indicates an expected call of ReadServiceConfig.
func (mr *MockConfluentHomeMockRecorder) ReadServiceConfig(service, zookeeperMode any) *MockConfluentHomeReadServiceConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadServiceConfig", reflect.TypeOf((*MockConfluentHome)(nil).ReadServiceConfig), service, zookeeperMode)
	return &MockConfluentHomeReadServiceConfigCall{Call: call}
}

// MockConfluentHomeReadServiceConfigCall wrap *gomock.Call
type MockConfluentHomeReadServiceConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfluentHomeReadServiceConfigCall) Return(arg0 []byte, arg1 error) *MockConfluentHomeReadServiceConfigCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfluentHomeReadServiceConfigCall) Do(f func(string, bool) ([]byte, error)) *MockConfluentHomeReadServiceConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfluentHomeReadServiceConfigCall) DoAndReturn(f func(string, bool) ([]byte, error)) *MockConfluentHomeReadServiceConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadServicePort mocks base method.
func (m *MockConfluentHome) ReadServicePort(service string, zookeeperMode bool) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadServicePort", service, zookeeperMode)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadServicePort indicates an expected call of ReadServicePort.
func (mr *MockConfluentHomeMockRecorder) ReadServicePort(service, zookeeperMode any) *MockConfluentHomeReadServicePortCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadServicePort", reflect.TypeOf((*MockConfluentHome)(nil).ReadServicePort), service, zookeeperMode)
	return &MockConfluentHomeReadServicePortCall{Call: call}
}

// MockConfluentHomeReadServicePortCall wrap *gomock.Call
type MockConfluentHomeReadServicePortCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfluentHomeReadServicePortCall) Return(arg0 int, arg1 error) *MockConfluentHomeReadServicePortCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfluentHomeReadServicePortCall) Do(f func(string, bool) (int, error)) *MockConfluentHomeReadServicePortCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfluentHomeReadServicePortCall) DoAndReturn(f func(string, bool) (int, error)) *MockConfluentHomeReadServicePortCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
