run:
  skip-dirs:
    - mock
linters:
  enable:
    - dupword
    - exportloopref
    - gci
    - gocritic
    - gofmt
    - goimports
    - gomoddirectives
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - nonamedreturns
    - prealloc
    - predeclared
    - tenv
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace 
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/confluentinc)
      - prefix(github.com/confluentinc/cli)
    custom-order: true
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
  nakedret:
    max-func-lines: 0
