run:
  skip-dirs:
    - mock
    - pkg/flink/test/mock
linters:
  enable:
    - dupword
    - exportloopref
    - gci
    - gofmt
    - goimports
    - gomoddirectives
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - nonamedreturns
    - prealloc
    - predeclared
    - tenv
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/confluentinc/)
      - prefix(github.com/confluentinc/cli/)
    custom-order: true
  nakedret:
    max-func-lines: 0
