project_name: confluent-cli

builds:
  -
    binary: confluent
    main: .
    ldflags:
      # remove the date so builds are reproducible (identical SHAs)
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
    gcflags:
      - -trimpath={{.Env.GOPATH}}
    asmflags:
      - -trimpath={{.Env.GOPATH}}
    goos:
      - linux
    goarch:
      - amd64
  -
    binary: ccloud-kafka-plugin
    main: ./plugin/confluent-kafka-plugin
    ldflags:
      # remove the date so builds are reproducible (identical SHAs)
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
    gcflags:
      - -trimpath={{.Env.GOPATH}}
    asmflags:
      - -trimpath={{.Env.GOPATH}}
    goos:
      - linux
    goarch:
      - amd64
  -
    binary: ccloud-connect-plugin
    main: ./plugin/confluent-connect-plugin
    ldflags:
      # remove the date so builds are reproducible (identical SHAs)
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
    gcflags:
      - -trimpath={{.Env.GOPATH}}
    asmflags:
      - -trimpath={{.Env.GOPATH}}
    goos:
      - linux
    goarch:
      - amd64
  -
    binary: ccloud-user-plugin
    main: ./plugin/confluent-user-plugin
    ldflags:
      # remove the date so builds are reproducible (identical SHAs)
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
    gcflags:
      - -trimpath={{.Env.GOPATH}}
    asmflags:
      - -trimpath={{.Env.GOPATH}}
    goos:
      - linux
    goarch:
      - amd64
  -
    binary: ccloud-api-key-plugin
    main: ./plugin/confluent-api-key-plugin
    ldflags:
      # remove the date so builds are reproducible (identical SHAs)
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
    gcflags:
      - -trimpath={{.Env.GOPATH}}
    asmflags:
      - -trimpath={{.Env.GOPATH}}
    goos:
      - linux
    goarch:
      - amd64
