project_name: confluent

dist: dist/confluent

builds:
  -
    binary: confluent
    main: cmd/confluent/main.go
    flags:
      - -mod=readonly
      - -tags=musl
    ldflags:
      - -s -w -X main.version={{.Env.VERSION}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}  -X main.host={{.Env.HOSTNAME}} -X main.cliName=confluent
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-musl-gcc
      - CXX=x86_64-linux-musl-g++
      - CGO_LDFLAGS=${CGO_LDFLAGS} -static
    goos:
      - linux
    goarch:
      - amd64
