project_name: ccloud

before:
  hooks:
    # to avoid goreleaser error due to `make deps` on CI: git is currently in a dirty state
    - git checkout go.mod

builds:
  -
    binary: ccloud
    main: .
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}  -X main.host={{.Env.HOSTNAME}}
    gcflags:
      - -trimpath={{.Env.GOPATH}}
    asmflags:
      - -trimpath={{.Env.GOPATH}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
  -
    binary: ccloud-kafka-plugin
    main: ./plugin/ccloud-kafka-plugin
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}  -X main.host={{.Env.HOSTNAME}}
    gcflags:
      - -trimpath={{.Env.GOPATH}}
    asmflags:
      - -trimpath={{.Env.GOPATH}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
  -
    binary: ccloud-connect-plugin
    main: ./plugin/ccloud-connect-plugin
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}  -X main.host={{.Env.HOSTNAME}}
    gcflags:
      - -trimpath={{.Env.GOPATH}}
    asmflags:
      - -trimpath={{.Env.GOPATH}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386

release:
  github:
    owner: confluentinc
    name: cli

  prerelease: false

archive:
  format: binary

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
    - ci skip

s3:
  -
    bucket: confluent.cloud
    region: us-west-2
    folder: "ccloud-cli/{{.Version}}"
    acl: public-read

#brew:
#  github:
#    owner: confluentinc
#    name: homebrew-ccloud
#  folder: Formula
#  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
#
#  homepage: https://confluent.io
#  description: Confluent Cloud CLI
#
#  commit_author:
#    name: Cody A. Ray
#    email: cody@confluent.io
#
#nfpm:
#  vendor: Confluent, Inc.
#  homepage: https://confluent.io
#  description: Confluent Cloud CLI
#  maintainer: Confluent Support <support@confluent.io>
#  license: Copyright 2018 Confluent, Inc.
#
#  formats:
#    - deb
#
#  replacements:
#    darwin: Darwin
#    linux: Linux
#    windows: Windows
#    386: i386
#    amd64: x86_64
