project_name: confluent

builds:
  - binary: confluent
    main: cmd/confluent/main.go
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X main.version={{.Env.VERSION}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    gcflags:
      - all=-trimpath={{.Env.HOME}}/git
    asmflags:
      - all=-trimpath={{.Env.HOME}}/git
    goos:
      - linux
    goarch:
      - arm64

release:
  disable: true

archives:
  - format: binary