project_name: ccloud

builds:
  -
    binary: ccloud
    main: .
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Env.VERSION}} -X main.commit={{.Commit}} -X main.date={{.Date}}  -X main.host={{.Env.HOSTNAME}}
    gcflags:
      - -trimpath={{.Env.GOPATH}}
    asmflags:
      - -trimpath={{.Env.GOPATH}}
    goos:
      - darwin
    goarch:
      - amd64
  -
    binary: ccloud-kafka-plugin
    main: ./plugin/ccloud-kafka-plugin
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Env.VERSION}} -X main.commit={{.Commit}} -X main.date={{.Date}}  -X main.host={{.Env.HOSTNAME}}
    gcflags:
      - -trimpath={{.Env.GOPATH}}
    asmflags:
      - -trimpath={{.Env.GOPATH}}
    goos:
      - darwin
    goarch:
      - amd64
#  -
#    binary: ccloud-connect-plugin
#    main: ./plugin/ccloud-connect-plugin
#    flags:
#      - -mod=readonly
#    ldflags:
#      - -s -w -X main.version={{.Env.VERSION}} -X main.commit={{.Commit}} -X main.date={{.Date}}  -X main.host={{.Env.HOSTNAME}}
#    gcflags:
#      - -trimpath={{.Env.GOPATH}}
#    asmflags:
#      - -trimpath={{.Env.GOPATH}}
#    goos:
#      - darwin
#    goarch:
#      - amd64
  -
    binary: ccloud-ksql-plugin
    main: ./plugin/ccloud-ksql-plugin
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Env.VERSION}} -X main.commit={{.Commit}} -X main.date={{.Date}}  -X main.host={{.Env.HOSTNAME}}
    gcflags:
      - -trimpath={{.Env.GOPATH}}
    asmflags:
      - -trimpath={{.Env.GOPATH}}
    goos:
      - darwin
    goarch:
      - amd64
  -
    binary: ccloud-user-plugin
    main: ./plugin/ccloud-user-plugin
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Env.VERSION}} -X main.commit={{.Commit}} -X main.date={{.Date}}  -X main.host={{.Env.HOSTNAME}}
    gcflags:
      - -trimpath={{.Env.GOPATH}}
    asmflags:
      - -trimpath={{.Env.GOPATH}}
    goos:
      - darwin
    goarch:
      - amd64
  -
    binary: ccloud-apikey-plugin
    main: ./plugin/ccloud-apikey-plugin
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Env.VERSION}} -X main.commit={{.Commit}} -X main.date={{.Date}}  -X main.host={{.Env.HOSTNAME}}
    gcflags:
      - -trimpath={{.Env.GOPATH}}
    asmflags:
      - -trimpath={{.Env.GOPATH}}
    goos:
      - darwin
    goarch:
      - amd64
  -
    binary: ccloud-environment-plugin
    main: ./plugin/ccloud-environment-plugin
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Env.VERSION}} -X main.commit={{.Commit}} -X main.date={{.Date}}  -X main.host={{.Env.HOSTNAME}}
    gcflags:
      - -trimpath={{.Env.GOPATH}}
    asmflags:
      - -trimpath={{.Env.GOPATH}}
    goos:
      - darwin
    goarch:
      - amd64
