project_name: confluent

dist: prebuilt

env:
  - CGO_ENABLED=1
  - GOEXPERIMENT=boringcrypto

builds:
  - id: confluent-linux-arm64
    binary: confluent
    main: cmd/confluent/main.go
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    gcflags:
      - all=-trimpath={{.Env.HOME}}/git
    asmflags:
      - all=-trimpath={{.Env.HOME}}/git
    goos:
      - linux
    goarch:
      - arm64
  - id: confluent-linux-arm64-disableupdates
    binary: confluent
    main: cmd/confluent/main.go
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.disableUpdates=true
    gcflags:
      - all=-trimpath={{.Env.HOME}}/git
    asmflags:
      - all=-trimpath={{.Env.HOME}}/git
    goos:
      - linux
    goarch:
      - arm64

release:
  disable: true

archives:
  - format: binary
