project_name: confluent

dist: prebuilt

builds:
  - id: confluent-linux-arm64
    binary: confluent
    main: cmd/confluent/main.go
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    gcflags:
      - all=-trimpath={{.Env.HOME}}/git
    asmflags:
      - all=-trimpath={{.Env.HOME}}/git
    goos:
      - linux
    goarch:
      - arm64
  - id: confluent-linux-arm64-disableupdates
    binary: confluent
    main: cmd/confluent/main.go
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.disableUpdates=true
    gcflags:
      - all=-trimpath={{.Env.HOME}}/git
    asmflags:
      - all=-trimpath={{.Env.HOME}}/git
    goos:
      - linux
    goarch:
      - arm64

nfpms:
  - package_name: confluent
    file_name_template: "{{ .ConventionalFileName }}"
    builds:
      - confluent-linux-arm64-disableupdates
    vendor: Confluent Inc.
    homepage: https://docs.confluent.io/confluent-cli/current/overview.html
    maintainer: Confluent Inc.
    description: CLI for Confluent Cloud and Confluent Platform
    license: Confluent Community License Agreement
    formats:
      - deb
      - rpm
    deb:
      signature:
        key_file: /run/secrets/deb_gpg_secret_key
    rpm:
      signature:
        key_file: /run/secrets/rpm_gpg_secret_key

release:
  disable: true

archives:
  - format: binary