project_name: confluent

dist: dist/rbac

builds:
  -
    binary: confluent
    main: cmd/confluent/main.go
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Env.VERSION}} -X main.commit={{.Commit}} -X main.date={{.Date}}  -X main.host={{.Env.HOSTNAME}} -X main.target=rbac
    gcflags:
      - -trimpath={{.Env.GOPATH}}
    asmflags:
      - -trimpath={{.Env.GOPATH}}
    goos:
      - linux
    goarch:
      - amd64
