project_name: ccloud

dist: dist/cloud

builds:
  -
    binary: ccloud
    main: cmd/confluent/main.go
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Env.VERSION}} -X main.commit={{.Commit}} -X main.date={{.Date}}  -X main.host={{.Env.HOSTNAME}} -X main.target=cloud
    gcflags:
      - -trimpath={{.Env.GOPATH}}
    asmflags:
      - -trimpath={{.Env.GOPATH}}
    goos:
      - darwin
    goarch:
      - amd64
