project_name: ccloud

dist: dist/ccloud

builds:
  -
    binary: ccloud
    main: cmd/confluent/main.go
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Env.VERSION}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}  -X main.host={{.Env.HOSTNAME}} -X main.cliName=ccloud
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    env:
      - CGO_ENABLED=1
      - SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk
    goos:
      - darwin
    goarch:
      - arm64
