project_name: confluent

dist: prebuilt

builds:
  - id: confluent-linux-amd64
    binary: confluent
    main: cmd/confluent/main.go
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X github.com/confluentinc/cli/internal/cmd/local.localArch=amd64
    gcflags:
      - all=-trimpath={{.Env.HOME}}/git
    asmflags:
      - all=-trimpath={{.Env.HOME}}/git
    goos:
      - linux
    goarch:
      - amd64
  - id: confluent-linux-amd64-homebrew
    binary: confluent
    main: cmd/confluent/main.go
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.disableUpdates=true -X github.com/confluentinc/cli/internal/cmd/local.localArch=amd64
    gcflags:
      - all=-trimpath={{.Env.HOME}}/git
    asmflags:
      - all=-trimpath={{.Env.HOME}}/git
    goos:
      - linux
    goarch:
      - amd64

release:
  disable: true

archives:
  - format: binary
