project_name: confluent

builds:
  - binary: confluent
    id: confluent-alpine-amd64
    main: cmd/confluent/main.go
    flags:
      - -mod=readonly
      - -tags=musl
    ldflags:
      - -s -w -X main.version={{.Env.VERSION}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    gcflags:
      - all=-trimpath={{.Env.HOME}}/git
    asmflags:
      - all=-trimpath={{.Env.HOME}}/git
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-musl-gcc
      - CXX=x86_64-linux-musl-g++
      - CGO_LDFLAGS=${CGO_LDFLAGS} -static
    goos:
      - linux
    goarch:
      - amd64
  - binary: confluent
    id: confluent-alpine-arm64
    main: cmd/confluent/main.go
    flags:
      - -mod=readonly
      - -tags=musl
    ldflags:
      - -s -w -X main.version={{.Env.VERSION}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    gcflags:
      - all=-trimpath={{.Env.HOME}}/git
    asmflags:
      - all=-trimpath={{.Env.HOME}}/git
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-musl-gcc
      - CXX=aarch64-linux-musl-g++
      - CGO_LDFLAGS=${CGO_LDFLAGS} -static
    goos:
      - linux
    goarch:
      - arm64
  - binary: confluent
    id: confluent-windows-amd64
    main: cmd/confluent/main.go
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Env.VERSION}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -buildmode=exe  
    gcflags:
      - all=-trimpath={{.Env.HOME}}/git
    asmflags:
      - all=-trimpath={{.Env.HOME}}/git
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
      - CGO_LDFLAGS=${CGO_LDFLAGS} -static
    goos:
      - windows
    goarch:
      - amd64
    hooks:
      pre:
        - cmd: az login
        - cmd: az keyvault secret download --file CLIEVCodeSigningCertificate2.pfx --name CLIEVCodeSigningCertificate2 --subscription cc-prod --vault-name CLICodeSigningKeyVault --encoding base64
        - cmd: xattr -dr com.apple.quarantine ./lib/osslsigncode
      post:
        - cmd: ./lib/osslsigncode sign -n "Confluent CLI" -i "https://confluent.io" -pkcs12 CLIEVCodeSigningCertificate2.pfx -in {{ .Path }} -out {{ .Path }}
        - cmd: rm CLIEVCodeSigningCertificate2.pfx
  - binary: confluent
    id: signed-amd64
    main: cmd/confluent/main.go
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Env.VERSION}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    gcflags:
      - all=-trimpath={{.Env.HOME}}/git
    asmflags:
      - all=-trimpath={{.Env.HOME}}/git
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post:
        - cmd: make download-licenses
        - cmd: scripts/gon_filepath_editor.sh {{ .Path }} amd64
        - cmd: gon dist/gon_confluent_amd64.hcl
  - binary: confluent
    id: signed-arm64
    main: cmd/confluent/main.go
    flags:
      - -mod=readonly
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{.Env.VERSION}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    gcflags:
      - all=-trimpath={{.Env.HOME}}/git
    asmflags:
      - all=-trimpath={{.Env.HOME}}/git
    goos:
      - darwin
    goarch:
      - arm64
    hooks:
      post:
        - cmd: scripts/gon_filepath_editor.sh {{ .Path }} arm64
        - cmd: gon dist/gon_confluent_arm64.hcl
  - builder: prebuilt
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    prebuilt:
      path: dist/confluent_{{ .Os }}_{{ .Arch }}_{{ with .Amd64 }}_v1{{ end }}/confluent

release:
  disable: "{{.Env.DRY_RUN}}"

archives:
  - id: binary
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "linux" }}alpine{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'
    format: binary
    rlcp: true
  - id: archive
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "linux" }}alpine{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'
    format: tar.gz
    rlcp: true
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: "{{ .ProjectName }}"
    files:
      - LICENSE
      - legal/**/*
    
blobs:
  - ids:
    - binary
    provider: s3
    bucket: confluent.cloud
    region: us-west-2
    folder: "{{.Env.S3FOLDER}}/binaries/{{.Version}}"
    disable: "{{.Env.DRY_RUN}}" 
  - ids:
    - archive
    provider: s3
    bucket: confluent.cloud
    region: us-west-2
    folder: "{{.Env.S3FOLDER}}/archives/{{.Version}}"
    disable: "{{.Env.DRY_RUN}}" 
