#Paste the following:
"name": "rANDOM"
"connector.class": "AzureBlobSink"
"azblob.account.name": "azsink"
"azblob.account.key": "9nyeTfcFoHg6NAyfntlWA0PR+bgld9SYZwNqahb4wHjcMUzRsYEb/Nfn7PpKudOVmsLH/qNRF97tK0ExjUo1gQ=="
"azblob.container.name": "sink-container"
"data.format": "JSON"
"time.interval": "HOURLY"
"topics": "apples"
"kafka.api.key": “A5CO2REBGUVP3EGI"
"kafka.api.secret": "0VsOKV6SKQYg4J399tN75xA94nAK5xOj3nVQcEbDEdKH8vNn82Wm9wqZW7mKwH92"
"tasks.max": "1"
