FROM mcr.microsoft.com/windows:1809 AS makeiso

ENV chocolateyUseWindowsCompression false

RUN powershell -NoProfile -ExecutionPolicy unrestricted -Command \
    iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1')); \
    choco feature disable --name showDownloadProgress

RUN choco install make && \
    choco install grep -y && \
    choco install sed -y && \
    choco install git -y && \
    choco install mingw -y && \
    choco install golang -y

RUN powershell $Env:Path+=';C:\Program Files\Git\bin\;C:\Program Files\Git\cmd\;C:\Program Files\Go\bin' && \
    powershell refreshenv

RUN powershell mkdir -p /go/src/github.com/goreleaser && \
    powershell cd /go/src/github.com/goreleaser && \
    powershell git clone https://github.com/goreleaser/goreleaser.git && \
    powershell cd goreleaser && \
    powershell git checkout v0.141.0 && \
    powershell go install . && \
    powershell mkdir -p /go/src/github.com/confluentinc/cli

COPY . /go/src/github.com/confluentinc/cli/

COPY .netrc /root/.netrc
RUN chmod 600 /root/.netrc

RUN cd /go/src/github.com/confluentinc/cli && \
    make gorelease-windows ; \
    for file in dist/ccloud/*linux*; do mv -v "$file" "${file/windows}"; done ; \
    for file in dist/confluent/*linux*; do mv -v "$file" "${file/windows}"; done ; \
    for file in dist/ccloud/*.txt; do mv -v "$file" "${file/checksums/checksums_windows}"; done; \
    for file in dist/ccloud/*.txt; do sed -i 's/windows/g' $file ; done; \
    for file in dist/confluent/*.txt; do mv -v "$file" "${file/checksums/checksums_windows}"; done; \
    for file in dist/confluent/*.txt; do sed -i 's/windows/g' $file ; done