FROM public.ecr.aws/j3p8s0n3/windows-2019:latest

RUN powershell mkdir -p /go/src/github.com/confluentinc/cli && \
    cd /go/src/github.com/confluentinc/cli

COPY .netrc /Users/ContainerAdministrator/

RUN powershell Rename-Item -Path "/Users/ContainerAdministrator/.netrc" -NewName "_netrc" && \
    cd Users/ContainerAdministrator && \
    powershell icacls _netrc /grant Everyone:F

COPY . /go/src/github.com/confluentinc/cli/

RUN powershell setx PATH \"$env:path;C:\go\src\github.com\confluentinc\cli\;C:\Program Files\Git\bin\" -m

RUN cd /go/src/github.com/confluentinc/cli && \
    make gorelease-windows ; 

RUN cd /go/src/github.com/confluentinc/cli && \
    for file in dist/ccloud/*windows*; do mv -v "$file" "${file/windows}"; done ; \
    for file in dist/confluent/*windows*; do mv -v "$file" "${file/windows}"; done ; \
    for file in dist/ccloud/*.txt; do mv -v "$file" "${file/checksums/checksums_windows}"; done; \
    for file in dist/ccloud/*.txt; do sed -i 's/windows/g' $file ; done; \
    for file in dist/confluent/*.txt; do mv -v "$file" "${file/checksums/checksums_windows}"; done; \
    for file in dist/confluent/*.txt; do sed -i 's/windows/g' $file ; done