jobs:
- job: system_test
  displayName: CLI System Tests
  timeoutInMinutes: 150 # 2h30m

  pool:
    vmImage: "ubuntu-18.04"
  
  variables:
    IMAGE_NAME: DUMMY_IMAGE_NAME # mk-include/docker.mk requires an image name (not needed for CLI system tests)
    CI: "true"
    BIN_PATH: $(Agent.BuildDirectory)
  
  steps:
  
  - template: azure-pipelines-templates/setup-secrets.yml

  - bash: |
      git clone git@github.com:confluentinc/cc-mk-include.git mk-include
      echo "include ./mk-include/cc-begin.mk" >> Makefile
      echo "include ./mk-include/cc-cpd.mk" >> Makefile
      echo "include ./mk-include/cc-docker.mk" >> Makefile
      echo "include ./mk-include/cc-helm.mk" >> Makefile
      echo "include ./mk-include/cc-vault.mk" >> Makefile
      echo "include ./mk-files/cli-cpd.mk" >> Makefile
    displayName: Add mk-include targets to Makefile

  - bash: make install-vault
    displayName: Install vault

  - task: DownloadSecureFile@1
    name: vaultsecrets
    inputs:
      secureFile: "vault_secrets"
    displayName: Securely download Vault environment variables
  
  - task: HelmInstaller@1 # Azure Pipelines preinstalls helm, replace it with version 3.3.4 specified in cc-helm.mk
    inputs:
      helmVersionToInstall: 3.3.4
    displayName: Install helm
  
  - bash: |
      export PATH="$(BIN_PATH):$PATH"
      . $(vaultsecrets.secureFilePath) # export VAULT_ADDR, VAULT_ROLE_ID, and VAULT_SECRET_ID
      . mk-include/bin/vault-setup
      . vault-sem-get-secret artifactory-docker-helm
      . vault-sem-get-secret aws_credentials
      . vault-sem-get-secret cpd_gcloud
      . vault-sem-get-secret eng_aws
      . vault-sem-get-secret gitconfig
      . vault-sem-get-secret netrc
      . vault-sem-get-secret semaphore-secrets-global
      . vault-sem-get-secret ssh_id_rsa
      . vault-sem-get-secret ssh_config
      make docker-login-ci
      make helm-setup-ci
      make helm-update-repo
    displayName: Inject Vault secrets, set up Docker and Helm

  - bash: make gcloud-install
    displayName: Install gcloud
  
  - bash: make cpd-update
    displayName: Install cpd
  
  - bash: |
      . $(vaultsecrets.secureFilePath)
      make cpd-priv-create-if-missing
    env:
      AZURE_PIPELINES: "true"
      AZURE_PIPELINES_JOB_ID: $(Build.BuildId)
      AZURE_PIPELINES_PROJECT_NAME: "cli"
      CPD_CR_ARGS: "--pool-name ci"
    displayName: Create CPD cluster
  
  - template: azure-pipelines-templates/setup-go.yml
  
  - bash: |
      echo "##vso[task.setvariable variable=GOROOT]$(BIN_PATH)/go"
      echo "##vso[task.setvariable variable=GOPATH]$(BIN_PATH)/gopath"
      echo "##vso[task.setvariable variable=GOBIN]$(BIN_PATH)/go/bin"
      echo "##vso[task.setvariable variable=modulePath]$(BIN_PATH)/go/src/github.com/$(build.repository.name)"
      echo "##vso[task.prependpath]$(GOROOT)/bin"
      echo "##vso[task.prependpath]$(GOPATH)/bin"
      mkdir -p ${GOPATH}\bin
      mkdir -p ${GOROOT}\bin
    displayName: Set up Go environment and workspace
  
  - bash: make deps
    displayName: Download Go dependencies
  
  - bash: make build
    displayName: Build CLI binary
  
  - task: GoTool@0
    inputs:
      version: "1.15.7"
    displayName: Use Go 1.15.7 for cc-system-tests
    
  - bash: make checkout-cc-system-tests
    displayName: Check out cc-system-tests
  
  - bash: |
      export PATH="$(BIN_PATH):$PATH"
      . $(vaultsecrets.secureFilePath)
      . mk-include/bin/vault-setup
      . vault-sem-get-secret cc-system-tests
      $(BIN_PATH)/cpd priv inject-credentials --id $(kubectl config current-context) --all-namespaces
    displayName: Get secret environment variables for cc-system-tests from Vault
  
  - bash: make cpd-priv-testenv || make cpd-debug-and-err
    displayName: Get environment variables for cc-system-tests

  - bash: make system-test-init-env || make cpd-debug-and-err
    env:
      CREATE_KAFKA_CLUSTERS: "true"
    displayName: Initialize CPD environment
  
  - bash: make replace-cli-binary
    displayName: Replace CLI binary

  - bash: |
      export PATH="$(BIN_PATH):$PATH"
      . $(vaultsecrets.secureFilePath)
      . mk-include/bin/vault-setup
      . vault-sem-get-secret azure_credentials
      . vault-sem-get-secret aws_credentials
      make run-system-tests
    env:
      GO_TEST_PACKAGE_ARGS: "./test/cli/..."
    displayName: Run system tests
  
  - bash: make cpd-destroy
    condition: always()
    displayName: Free CPD
