// Code generated by cli-terraform-generator v0.35.0; DO NOT EDIT.

package configurationcontrol

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/output"
)

func (c *policyCommand) newListCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List Configuration Control policies.",
		Args:  cobra.NoArgs,
		RunE:  c.list,
	}

	// Required flags

	// Optional flags

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *policyCommand) list(cmd *cobra.Command, _ []string) error {
	policies, err := c.V2Client.ListConfigurationcontrolPolicies()
	if err != nil {
		return err
	}

	list := output.NewList(cmd)
	for _, policy := range policies {
		out := &policyOut{
			Name:              policy.Metadata.GetName(),
			Action:            policy.Spec.GetAction(),
			Type:              policy.Spec.GetType(),
			ScopeResourceName: policy.Spec.Scope.GetResourceName(),
			Mode:              policy.Spec.GetMode(),
			Rules:             policy.Spec.GetRules(),
		}
		list.Add(out)
	}
	return list.Print()
}
