// Code generated by cli-terraform-generator v0.35.0; DO NOT EDIT.

package configurationcontrol

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/config"
)

func New(cfg *config.Config, prerunner pcmd.PreRunner) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "configurationcontrol",
		Short: "Manage Configuration Control.",
	}

	cmd.AddCommand(
		newPolicyCommand(cfg, prerunner),
		// cli-tfgen:cli-subcommands
	)

	return cmd
}
