// Code generated by cli-terraform-generator v0.35.0; DO NOT EDIT.

package configurationcontrol

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
)

func (c *policyCommand) newDescribeCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "describe <name>",
		Short:             "Describe a configurationcontrol policy.",
		Args:              cobra.ExactArgs(1),
		ValidArgsFunction: pcmd.NewValidArgsFunction(c.validArgs),
		RunE:              c.describe,
	}

	// Required flags

	// Optional flags

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *policyCommand) describe(cmd *cobra.Command, args []string) error {
	name := args[0]

	policy, err := c.V2Client.GetConfigurationcontrolPolicy(name)
	if err != nil {
		return err
	}

	return printPolicy(cmd, policy)
}
