// Code generated by cli-terraform-generator v0.11.2; DO NOT EDIT.

package ccpm

import (
	"strings"

	"github.com/spf13/cobra"

	ccpmv1 "github.com/confluentinc/ccloud-sdk-go-v2/ccpm/v1"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
	"github.com/confluentinc/cli/v4/pkg/examples"
)

func (c *customConnectPluginCommand) newCreateCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a CCPM custom Connect plugin.",
		Args:  cobra.NoArgs,
		RunE:  c.create,
		Example: examples.BuildExampleString(
			examples.Example{
				Text: "Create a custom Connect plugin for AWS.",
				Code: `confluent ccpm plugin create --name "My Custom Plugin" --cloud AWS --description "A custom connector for data processing" --environment env-12345`,
			},
			examples.Example{
				Text: "Create a custom Connect plugin for GCP with minimal description.",
				Code: `confluent ccpm plugin create --name "GCP Data Connector" --cloud GCP --environment env-abcdef`,
			},
		),
	}

	// Required flags
	pcmd.AddCloudFlag(cmd)
	cmd.Flags().String("name", "", "Display name of Custom Connect Plugin.")
	cobra.CheckErr(cmd.MarkFlagRequired("cloud"))
	cobra.CheckErr(cmd.MarkFlagRequired("name"))

	// Optional flags
	cmd.Flags().String("description", "", "Description of Custom Connect Plugin.")
	pcmd.AddEnvironmentFlag(cmd, c.AuthenticatedCLICommand)

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *customConnectPluginCommand) create(cmd *cobra.Command, args []string) error {
	spec := ccpmv1.CcpmV1CustomConnectPluginSpec{}
	createReq := ccpmv1.CcpmV1CustomConnectPlugin{}

	cloud, err := cmd.Flags().GetString("cloud")
	if err != nil {
		return err
	}
	cloud = strings.ToUpper(cloud)
	spec.Cloud = ccpmv1.PtrString(cloud)

	description, err := cmd.Flags().GetString("description")
	if err != nil {
		return err
	}
	if description != "" {
		spec.Description = ccpmv1.PtrString(description)
	}

	displayName, err := cmd.Flags().GetString("name")
	if err != nil {
		return err
	}
	spec.DisplayName = ccpmv1.PtrString(displayName)

	environmentId, err := c.Context.EnvironmentId()
	if err != nil {
		return err
	}
	spec.Environment = &ccpmv1.EnvScopedObjectReference{Id: environmentId}

	createReq.Spec = &spec
	customConnectPlugin, httpResp, err := c.V2Client.CreateCcpmCustomConnectPlugin(createReq)
	if err != nil {
		return errors.CatchCCloudV2Error(err, httpResp)
	}

	return printCustomConnectPlugin(cmd, customConnectPlugin)
}
