//go:build live_test && (all || flink)

// Code generated by cli-terraform-generator v0.7.0; DO NOT EDIT.

package live

import (
	"testing"
)

func (s *CLILiveTestSuite) TestFlinkComputePoolConfigCRUDLive() {
	t := s.T()
	t.Parallel()
	state := s.setupTestContext(t)

	// Variables
	updatedDefaultPoolEnabled := "true"
	updatedDefaultPoolMaxCfu := "25"

	// Cleanup (LIFO — execution is reverse-registration order)

	steps := []CLILiveTest{
		{
			Name:            "Describe Flink org compute pool config",
			Args:            "flink compute-pool-config describe -o json",
			UseStateVars:    true,
			ExitCode:        0,
			JSONFieldsExist: []string{"organization_id"},
		},
		{
			Name:         "Update Flink org compute pool config default-pool",
			Args:         "flink compute-pool-config update --default-pool=" + updatedDefaultPoolEnabled,
			UseStateVars: true,
			ExitCode:     0,
		},
		{
			Name:         "Update Flink org compute pool config max-cfu",
			Args:         "flink compute-pool-config update --max-cfu " + updatedDefaultPoolMaxCfu,
			UseStateVars: true,
			ExitCode:     0,
		},
		{
			Name:         "Verify Flink org compute pool config update",
			Args:         "flink compute-pool-config describe -o json",
			UseStateVars: true,
			ExitCode:     0,
			JSONFields: map[string]string{
				"default_pool_enabled": updatedDefaultPoolEnabled,
				"default_pool_max_cfu": updatedDefaultPoolMaxCfu,
			},
		},
	}

	for _, step := range steps {
		t.Run(step.Name, func(t *testing.T) {
			s.runLiveCommand(t, step, state)
		})
	}
}
