//go:build live_test && (all || flink)

// Code generated by cli-terraform-generator; DO NOT EDIT.

package live

import (
	"testing"
)

func (s *CLILiveTestSuite) TestFlinkRegionCRUDLive() {
	t := s.T()
	t.Parallel()
	state := s.setupTestContext(t)

	// Cleanup (LIFO — execution is reverse-registration order)

	steps := []CLILiveTest{
		{
			Name:         "List Flink regions",
			Args:         "flink region list",
			UseStateVars: true,
			ExitCode:     0,
		},
	}

	for _, step := range steps {
		t.Run(step.Name, func(t *testing.T) {
			s.runLiveCommand(t, step, state)
		})
	}
}
