//go:build live_test && (all || iam)

// Code generated by cli-terraform-generator v0.12.1; DO NOT EDIT.

package live

import (
	"testing"
)

func (s *CLILiveTestSuite) TestIamUserCRUDLive() {
	t := s.T()
	t.Parallel()
	state := s.setupTestContext(t)

	// Variables
	updatedFullName := "updated-live-test-full-name"

	// Cleanup (LIFO — execution is reverse-registration order)
	s.registerCleanup(t, "iam user delete {{.user_id}} --force", state)

	steps := []CLILiveTest{
		{
			Name:         "Describe IAM user",
			Args:         "iam user describe {{.user_id}} -o json",
			UseStateVars: true,
			ExitCode:     0,
		},
		{
			Name:         "List IAM users",
			Args:         "iam user list",
			UseStateVars: true,
			ExitCode:     0,
		},
		{
			Name:         "Update IAM user full-name",
			Args:         "iam user update {{.user_id}} --full-name " + updatedFullName,
			UseStateVars: true,
			ExitCode:     0,
		},
		{
			Name:         "Verify IAM user update",
			Args:         "iam user describe {{.user_id}} -o json",
			UseStateVars: true,
			ExitCode:     0,
			JSONFields: map[string]string{
				"full_name": updatedFullName,
			},
		},
		{
			Name:         "Delete IAM user",
			Args:         "iam user delete {{.user_id}} --force",
			UseStateVars: true,
			ExitCode:     0,
		},
		{
			Name:         "Verify deletion",
			Args:         "iam user describe {{.user_id}}",
			UseStateVars: true,
			ExitCode:     1,
		},
	}

	for _, step := range steps {
		t.Run(step.Name, func(t *testing.T) {
			s.runLiveCommand(t, step, state)
		})
	}
}
