//go:build live_test && (all || notifications)

// Code generated by cli-terraform-generator; DO NOT EDIT.

package live

import (
	"testing"
)

func (s *CLILiveTestSuite) TestNotificationsNotificationTypeCRUDLive() {
	t := s.T()
	t.Parallel()
	state := s.setupTestContext(t)

	// Variables
	notificationTypeName := uniqueName("notifi")

	// Cleanup (LIFO — execution is reverse-registration order)

	steps := []CLILiveTest{
		{
			Name:         "Describe notifications notification type",
			Args:         "notifications notification-type describe {{.notification_type_id}} -o json",
			UseStateVars: true,
			ExitCode:     0,
			JSONFields: map[string]string{
				"name": notificationTypeName,
			},
		},
		{
			Name:         "List notifications notification types",
			Args:         "notifications notification-type list",
			UseStateVars: true,
			ExitCode:     0,
			Contains:     []string{notificationTypeName},
		},
	}

	for _, step := range steps {
		t.Run(step.Name, func(t *testing.T) {
			s.runLiveCommand(t, step, state)
		})
	}
}
