//go:build live_test && (all || core)

// Code generated by cli-terraform-generator; DO NOT EDIT.

package live

import (
	"testing"
)

func (s *CLILiveTestSuite) TestOrganizationCRUDLive() {
	t := s.T()
	t.Parallel()
	state := s.setupTestContext(t)

	// Variables
	organizationName := uniqueName("organi")
	updatedJitEnabled := "true"

	// Cleanup (LIFO — execution is reverse-registration order)

	steps := []CLILiveTest{
		{
			Name:         "Describe organization",
			Args:         "organization describe -o json",
			UseStateVars: true,
			ExitCode:     0,
		},
		{
			Name:         "List organizations",
			Args:         "organization list",
			UseStateVars: true,
			ExitCode:     0,
		},
		{
			Name:         "Update organization name",
			Args:         "organization update --name " + organizationName + "-updated",
			UseStateVars: true,
			ExitCode:     0,
		},
		{
			Name:         "Update organization jit-enabled",
			Args:         "organization update --jit-enabled " + updatedJitEnabled,
			UseStateVars: true,
			ExitCode:     0,
		},
		{
			Name:         "Verify organization update",
			Args:         "organization describe -o json",
			UseStateVars: true,
			ExitCode:     0,
			JSONFields: map[string]string{
				"jit_enabled": updatedJitEnabled,
			},
		},
	}

	for _, step := range steps {
		t.Run(step.Name, func(t *testing.T) {
			s.runLiveCommand(t, step, state)
		})
	}
}
