//go:build live_test && (all || rtce)

// Code generated by cli-terraform-generator; DO NOT EDIT.

package live

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func (s *CLILiveTestSuite) TestRtceTopicCRUDLive() {
	t := s.T()
	t.Parallel()
	state := s.setupTestContext(t)

	// Setup for extra prereqs
	schemaContent := `{"type":"record","name":"PrereqValue","fields":[{"name":"id","type":"string"}]}`
	schemaDir, err := os.MkdirTemp("", "cli-live-schema-*")
	require.NoError(t, err)
	t.Cleanup(func() { os.RemoveAll(schemaDir) })
	schemaFile := filepath.Join(schemaDir, "schema.avsc")
	require.NoError(t, os.WriteFile(schemaFile, []byte(schemaContent), 0o644))

	// Variables
	cloud := "AWS"
	description := "live-test-description"
	region := "us-east-1"
	topicName := "orders_topic"
	updatedDescription := "updated-live-test-description"

	// Cleanup (LIFO — execution is reverse-registration order)
	s.registerCleanup(t, "environment delete {{.env_id}} --force", state)
	s.registerCleanup(t, "kafka cluster delete {{.kafka_cluster_id}} --environment {{.env_id}} --force", state)
	s.registerCleanup(t, "schema-registry schema delete --subject "+topicName+"-value --version all --force --environment {{.env_id}}", state)
	s.registerCleanup(t, "rtce rtce-topic delete "+topicName+" --environment {{.env_id}} --force", state)

	// Prereq group 0
	prereqSteps0 := []CLILiveTest{
		{
			Name:            "Create environment",
			Args:            "environment create " + uniqueName("env") + " -o json",
			CaptureID:       "env_id",
			JSONFieldsExist: []string{"id"},
		},
		{
			Name:         "Use environment",
			Args:         "environment use {{.env_id}}",
			UseStateVars: true,
		},
	}
	for _, step := range prereqSteps0 {
		t.Run(step.Name, func(t *testing.T) {
			s.runLiveCommand(t, step, state)
		})
	}

	// Prereq group 1 (async — wait follows)
	prereqSteps1 := []CLILiveTest{
		{
			Name:            "Create kafka cluster",
			Args:            "kafka cluster create " + uniqueName("clstr") + " --cloud " + cloud + " --region " + region + " --type basic -o json",
			CaptureID:       "kafka_cluster_id",
			JSONFieldsExist: []string{"id"},
		},
	}
	for _, step := range prereqSteps1 {
		t.Run(step.Name, func(t *testing.T) {
			s.runLiveCommand(t, step, state)
		})
	}

	t.Run("Wait for kafka cluster ready", func(t *testing.T) {
		s.waitForCondition(t,
			"kafka cluster describe {{.kafka_cluster_id}} --environment {{.env_id}} -o json",
			state,
			func(output string) bool {
				status := extractJSONField(t, output, "status")
				return strings.EqualFold(status, "UP") || strings.EqualFold(status, "PROVISIONED")
			},
			30*time.Second,
			10*time.Minute,
		)
	})

	// Prereq group 2
	prereqSteps2 := []CLILiveTest{
		{
			Name:         "Use kafka cluster",
			Args:         "kafka cluster use {{.kafka_cluster_id}}",
			UseStateVars: true,
		},
		{
			Name: "Create kafka topic",
			Args: "kafka topic create " + topicName + " --partitions 6",
		},
		{
			Name:            "Register AVRO schema for topic value subject",
			Args:            "schema-registry schema create --subject " + topicName + "-value --schema " + schemaFile + " --type avro --environment {{.env_id}} -o json",
			UseStateVars:    true,
			JSONFieldsExist: []string{"id"},
		},
	}
	for _, step := range prereqSteps2 {
		t.Run(step.Name, func(t *testing.T) {
			s.runLiveCommand(t, step, state)
		})
	}

	// Create the resource under test
	createSteps := []CLILiveTest{
		{
			Name:         "Create RTCE topic",
			Args:         "rtce rtce-topic create --cloud " + cloud + " --description " + description + " --region " + region + " --topic-name " + topicName + " --environment {{.env_id}} -o json",
			UseStateVars: true,
			JSONFields:   map[string]string{},
		},
	}

	for _, step := range createSteps {
		t.Run(step.Name, func(t *testing.T) {
			s.runLiveCommand(t, step, state)
		})
	}

	// Wait for the resource to reach its ready state. The condition accepts
	// any of the spec-declared target states (any-of semantics).
	t.Run("Wait for RTCE topic ready", func(t *testing.T) {
		s.waitForCondition(t,
			"rtce rtce-topic describe "+topicName+" --environment {{.env_id}} -o json",
			state,
			func(output string) bool {
				status := extractJSONField(t, output, "phase")
				return strings.EqualFold(status, "ACTIVE")
			},
			30*time.Second,
			10*time.Minute,
		)
	})

	// CRUD operations
	crudSteps := []CLILiveTest{
		{
			Name:         "Describe RTCE topic",
			Args:         "rtce rtce-topic describe " + topicName + " --environment {{.env_id}} -o json",
			UseStateVars: true,
			JSONFields:   map[string]string{},
		},
		{
			Name:         "List RTCE topics",
			Args:         "rtce rtce-topic list --environment {{.env_id}}",
			UseStateVars: true,
		},
		{
			Name:         "Update RTCE topic description",
			Args:         "rtce rtce-topic update " + topicName + " --description " + updatedDescription + " --environment {{.env_id}}",
			UseStateVars: true,
		},
		{
			Name:         "Delete RTCE topic",
			Args:         "rtce rtce-topic delete " + topicName + " --environment {{.env_id}} --force",
			UseStateVars: true,
		},
		{
			Name:         "Verify deletion",
			Args:         "rtce rtce-topic describe " + topicName + " --environment {{.env_id}}",
			UseStateVars: true,
			ExitCode:     1,
		},
	}

	for _, step := range crudSteps {
		t.Run(step.Name, func(t *testing.T) {
			s.runLiveCommand(t, step, state)
		})
	}
}
