//go:build live_test && (all || core)

// Code generated by cli-terraform-generator; DO NOT EDIT.

package live

import (
	"testing"
)

func (s *CLILiveTestSuite) TestScimTokenCRUDLive() {
	t := s.T()
	t.Parallel()
	state := s.setupTestContext(t)

	// Cleanup (LIFO — execution is reverse-registration order)
	s.registerCleanup(t, "organization scim-token delete {{.scim_token_id}} --force", state)

	steps := []CLILiveTest{
		{
			Name:            "Create organization scim token",
			Args:            "organization scim-token create -o json",
			ExitCode:        0,
			JSONFieldsExist: []string{"id"},
			CaptureID:       "scim_token_id",
		},
		{
			Name:         "List organization scim tokens",
			Args:         "organization scim-token list",
			UseStateVars: true,
			ExitCode:     0,
		},
		{
			Name:         "Delete organization scim token",
			Args:         "organization scim-token delete {{.scim_token_id}} --force",
			UseStateVars: true,
			ExitCode:     0,
		},
	}

	for _, step := range steps {
		t.Run(step.Name, func(t *testing.T) {
			s.runLiveCommand(t, step, state)
		})
	}
}
