// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/confluentinc/cli/v4/pkg/io (interfaces: FileSystem)
//
// Generated by this command:
//
//	mockgen -typed -destination=../mock/filesystem.go -package=mock github.com/confluentinc/cli/v4/pkg/io FileSystem
//

// Package mock is a generated GoMock package.
package mock

import (
	io0 "io"
	os "os"
	reflect "reflect"
	time "time"

	io "github.com/confluentinc/cli/v4/pkg/io"
	gomock "go.uber.org/mock/gomock"
)

// MockFileSystem is a mock of FileSystem interface.
type MockFileSystem struct {
	ctrl     *gomock.Controller
	recorder *MockFileSystemMockRecorder
	isgomock struct{}
}

// MockFileSystemMockRecorder is the mock recorder for MockFileSystem.
type MockFileSystemMockRecorder struct {
	mock *MockFileSystem
}

// NewMockFileSystem creates a new mock instance.
func NewMockFileSystem(ctrl *gomock.Controller) *MockFileSystem {
	mock := &MockFileSystem{ctrl: ctrl}
	mock.recorder = &MockFileSystemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileSystem) EXPECT() *MockFileSystemMockRecorder {
	return m.recorder
}

// Chmod mocks base method.
func (m *MockFileSystem) Chmod(name string, mode os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chmod", name, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chmod indicates an expected call of Chmod.
func (mr *MockFileSystemMockRecorder) Chmod(name, mode any) *MockFileSystemChmodCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chmod", reflect.TypeOf((*MockFileSystem)(nil).Chmod), name, mode)
	return &MockFileSystemChmodCall{Call: call}
}

// MockFileSystemChmodCall wrap *gomock.Call
type MockFileSystemChmodCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileSystemChmodCall) Return(arg0 error) *MockFileSystemChmodCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileSystemChmodCall) Do(f func(string, os.FileMode) error) *MockFileSystemChmodCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileSystemChmodCall) DoAndReturn(f func(string, os.FileMode) error) *MockFileSystemChmodCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Chtimes mocks base method.
func (m *MockFileSystem) Chtimes(name string, atime, mtime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chtimes", name, atime, mtime)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chtimes indicates an expected call of Chtimes.
func (mr *MockFileSystemMockRecorder) Chtimes(name, atime, mtime any) *MockFileSystemChtimesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chtimes", reflect.TypeOf((*MockFileSystem)(nil).Chtimes), name, atime, mtime)
	return &MockFileSystemChtimesCall{Call: call}
}

// MockFileSystemChtimesCall wrap *gomock.Call
type MockFileSystemChtimesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileSystemChtimesCall) Return(arg0 error) *MockFileSystemChtimesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileSystemChtimesCall) Do(f func(string, time.Time, time.Time) error) *MockFileSystemChtimesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileSystemChtimesCall) DoAndReturn(f func(string, time.Time, time.Time) error) *MockFileSystemChtimesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Copy mocks base method.
func (m *MockFileSystem) Copy(dst io0.Writer, src io0.Reader) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", dst, src)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Copy indicates an expected call of Copy.
func (mr *MockFileSystemMockRecorder) Copy(dst, src any) *MockFileSystemCopyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockFileSystem)(nil).Copy), dst, src)
	return &MockFileSystemCopyCall{Call: call}
}

// MockFileSystemCopyCall wrap *gomock.Call
type MockFileSystemCopyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileSystemCopyCall) Return(arg0 int64, arg1 error) *MockFileSystemCopyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileSystemCopyCall) Do(f func(io0.Writer, io0.Reader) (int64, error)) *MockFileSystemCopyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileSystemCopyCall) DoAndReturn(f func(io0.Writer, io0.Reader) (int64, error)) *MockFileSystemCopyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockFileSystem) Create(name string) (io.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name)
	ret0, _ := ret[0].(io.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFileSystemMockRecorder) Create(name any) *MockFileSystemCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFileSystem)(nil).Create), name)
	return &MockFileSystemCreateCall{Call: call}
}

// MockFileSystemCreateCall wrap *gomock.Call
type MockFileSystemCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileSystemCreateCall) Return(arg0 io.File, arg1 error) *MockFileSystemCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileSystemCreateCall) Do(f func(string) (io.File, error)) *MockFileSystemCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileSystemCreateCall) DoAndReturn(f func(string) (io.File, error)) *MockFileSystemCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Glob mocks base method.
func (m *MockFileSystem) Glob(pattern string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Glob", pattern)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Glob indicates an expected call of Glob.
func (mr *MockFileSystemMockRecorder) Glob(pattern any) *MockFileSystemGlobCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Glob", reflect.TypeOf((*MockFileSystem)(nil).Glob), pattern)
	return &MockFileSystemGlobCall{Call: call}
}

// MockFileSystemGlobCall wrap *gomock.Call
type MockFileSystemGlobCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileSystemGlobCall) Return(arg0 []string, arg1 error) *MockFileSystemGlobCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileSystemGlobCall) Do(f func(string) ([]string, error)) *MockFileSystemGlobCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileSystemGlobCall) DoAndReturn(f func(string) ([]string, error)) *MockFileSystemGlobCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsTerminal mocks base method.
func (m *MockFileSystem) IsTerminal(fd uintptr) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTerminal", fd)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsTerminal indicates an expected call of IsTerminal.
func (mr *MockFileSystemMockRecorder) IsTerminal(fd any) *MockFileSystemIsTerminalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTerminal", reflect.TypeOf((*MockFileSystem)(nil).IsTerminal), fd)
	return &MockFileSystemIsTerminalCall{Call: call}
}

// MockFileSystemIsTerminalCall wrap *gomock.Call
type MockFileSystemIsTerminalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileSystemIsTerminalCall) Return(arg0 bool) *MockFileSystemIsTerminalCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileSystemIsTerminalCall) Do(f func(uintptr) bool) *MockFileSystemIsTerminalCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileSystemIsTerminalCall) DoAndReturn(f func(uintptr) bool) *MockFileSystemIsTerminalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MkdirTemp mocks base method.
func (m *MockFileSystem) MkdirTemp(dir, prefix string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirTemp", dir, prefix)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MkdirTemp indicates an expected call of MkdirTemp.
func (mr *MockFileSystemMockRecorder) MkdirTemp(dir, prefix any) *MockFileSystemMkdirTempCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirTemp", reflect.TypeOf((*MockFileSystem)(nil).MkdirTemp), dir, prefix)
	return &MockFileSystemMkdirTempCall{Call: call}
}

// MockFileSystemMkdirTempCall wrap *gomock.Call
type MockFileSystemMkdirTempCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileSystemMkdirTempCall) Return(arg0 string, arg1 error) *MockFileSystemMkdirTempCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileSystemMkdirTempCall) Do(f func(string, string) (string, error)) *MockFileSystemMkdirTempCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileSystemMkdirTempCall) DoAndReturn(f func(string, string) (string, error)) *MockFileSystemMkdirTempCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Move mocks base method.
func (m *MockFileSystem) Move(src, dst string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Move", src, dst)
	ret0, _ := ret[0].(error)
	return ret0
}

// Move indicates an expected call of Move.
func (mr *MockFileSystemMockRecorder) Move(src, dst any) *MockFileSystemMoveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Move", reflect.TypeOf((*MockFileSystem)(nil).Move), src, dst)
	return &MockFileSystemMoveCall{Call: call}
}

// MockFileSystemMoveCall wrap *gomock.Call
type MockFileSystemMoveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileSystemMoveCall) Return(arg0 error) *MockFileSystemMoveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileSystemMoveCall) Do(f func(string, string) error) *MockFileSystemMoveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileSystemMoveCall) DoAndReturn(f func(string, string) error) *MockFileSystemMoveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NewBufferedReader mocks base method.
func (m *MockFileSystem) NewBufferedReader(rd io0.Reader) io.Reader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewBufferedReader", rd)
	ret0, _ := ret[0].(io.Reader)
	return ret0
}

// NewBufferedReader indicates an expected call of NewBufferedReader.
func (mr *MockFileSystemMockRecorder) NewBufferedReader(rd any) *MockFileSystemNewBufferedReaderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewBufferedReader", reflect.TypeOf((*MockFileSystem)(nil).NewBufferedReader), rd)
	return &MockFileSystemNewBufferedReaderCall{Call: call}
}

// MockFileSystemNewBufferedReaderCall wrap *gomock.Call
type MockFileSystemNewBufferedReaderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileSystemNewBufferedReaderCall) Return(arg0 io.Reader) *MockFileSystemNewBufferedReaderCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileSystemNewBufferedReaderCall) Do(f func(io0.Reader) io.Reader) *MockFileSystemNewBufferedReaderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileSystemNewBufferedReaderCall) DoAndReturn(f func(io0.Reader) io.Reader) *MockFileSystemNewBufferedReaderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Open mocks base method.
func (m *MockFileSystem) Open(name string) (io.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(io.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockFileSystemMockRecorder) Open(name any) *MockFileSystemOpenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockFileSystem)(nil).Open), name)
	return &MockFileSystemOpenCall{Call: call}
}

// MockFileSystemOpenCall wrap *gomock.Call
type MockFileSystemOpenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileSystemOpenCall) Return(arg0 io.File, arg1 error) *MockFileSystemOpenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileSystemOpenCall) Do(f func(string) (io.File, error)) *MockFileSystemOpenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileSystemOpenCall) DoAndReturn(f func(string) (io.File, error)) *MockFileSystemOpenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadDir mocks base method.
func (m *MockFileSystem) ReadDir(dirname string) ([]os.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", dirname)
	ret0, _ := ret[0].([]os.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockFileSystemMockRecorder) ReadDir(dirname any) *MockFileSystemReadDirCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockFileSystem)(nil).ReadDir), dirname)
	return &MockFileSystemReadDirCall{Call: call}
}

// MockFileSystemReadDirCall wrap *gomock.Call
type MockFileSystemReadDirCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileSystemReadDirCall) Return(arg0 []os.DirEntry, arg1 error) *MockFileSystemReadDirCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileSystemReadDirCall) Do(f func(string) ([]os.DirEntry, error)) *MockFileSystemReadDirCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileSystemReadDirCall) DoAndReturn(f func(string) ([]os.DirEntry, error)) *MockFileSystemReadDirCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Remove mocks base method.
func (m *MockFileSystem) Remove(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockFileSystemMockRecorder) Remove(name any) *MockFileSystemRemoveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockFileSystem)(nil).Remove), name)
	return &MockFileSystemRemoveCall{Call: call}
}

// MockFileSystemRemoveCall wrap *gomock.Call
type MockFileSystemRemoveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileSystemRemoveCall) Return(arg0 error) *MockFileSystemRemoveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileSystemRemoveCall) Do(f func(string) error) *MockFileSystemRemoveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileSystemRemoveCall) DoAndReturn(f func(string) error) *MockFileSystemRemoveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveAll mocks base method.
func (m *MockFileSystem) RemoveAll(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *MockFileSystemMockRecorder) RemoveAll(path any) *MockFileSystemRemoveAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockFileSystem)(nil).RemoveAll), path)
	return &MockFileSystemRemoveAllCall{Call: call}
}

// MockFileSystemRemoveAllCall wrap *gomock.Call
type MockFileSystemRemoveAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileSystemRemoveAllCall) Return(arg0 error) *MockFileSystemRemoveAllCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileSystemRemoveAllCall) Do(f func(string) error) *MockFileSystemRemoveAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileSystemRemoveAllCall) DoAndReturn(f func(string) error) *MockFileSystemRemoveAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Stat mocks base method.
func (m *MockFileSystem) Stat(name string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", name)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockFileSystemMockRecorder) Stat(name any) *MockFileSystemStatCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockFileSystem)(nil).Stat), name)
	return &MockFileSystemStatCall{Call: call}
}

// MockFileSystemStatCall wrap *gomock.Call
type MockFileSystemStatCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileSystemStatCall) Return(arg0 os.FileInfo, arg1 error) *MockFileSystemStatCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileSystemStatCall) Do(f func(string) (os.FileInfo, error)) *MockFileSystemStatCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileSystemStatCall) DoAndReturn(f func(string) (os.FileInfo, error)) *MockFileSystemStatCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
