// Code generated by cli-terraform-generator v0.7.2; DO NOT EDIT.

package flink

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
)

func (c *orgComputePoolConfigCommand) newDescribeCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "describe",
		Short: "Describe the Flink org compute pool config.",
		Args:  cobra.NoArgs,
		RunE:  c.describe,
	}

	// Required flags

	// Optional flags

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *orgComputePoolConfigCommand) describe(cmd *cobra.Command, _ []string) error {

	orgComputePoolConfig, httpResp, err := c.V2Client.GetFlinkOrgComputePoolConfig()
	if err != nil {
		return errors.CatchCCloudV2Error(err, httpResp)
	}

	return printOrgComputePoolConfig(cmd, orgComputePoolConfig)
}
