// Code generated by cli-terraform-generator v1.0.0; DO NOT EDIT.

package flink

import (
	"fmt"

	"github.com/hashicorp/go-multierror"
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/deletion"
	"github.com/confluentinc/cli/v4/pkg/errors"
	"github.com/confluentinc/cli/v4/pkg/output"
	"github.com/confluentinc/cli/v4/pkg/plural"
	"github.com/confluentinc/cli/v4/pkg/utils"
)

func (c *computePoolCommand) newDeleteCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "delete <id-1> [id-2] ... [id-n]",
		Short:             "Delete one or more Flink compute pools.",
		Args:              cobra.MinimumNArgs(1),
		ValidArgsFunction: pcmd.NewValidArgsFunction(c.validArgsMultiple),
		RunE:              c.delete,
	}

	// Required flags

	// Optional flags
	pcmd.AddEnvironmentFlag(cmd, c.AuthenticatedCLICommand)

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddForceFlag(cmd)

	return cmd
}

func (c *computePoolCommand) delete(cmd *cobra.Command, args []string) error {
	environmentId, err := c.Context.EnvironmentId()
	if err != nil {
		return err
	}

	existenceFunc := func(primaryId string) bool {
		_, _, err := c.V2Client.GetFlinkComputePool(primaryId, environmentId)
		return err == nil
	}

	if err := deletion.ValidateAndConfirm(cmd, args, existenceFunc, "Flink compute pool"); err != nil {
		return err
	}

	deleteFunc := func(primaryId string) error {
		return c.V2Client.DeleteFlinkComputePool(primaryId, environmentId)
	}

	deletedIds, err := deletion.DeleteWithoutMessage(cmd, args, deleteFunc)
	deleteMsg := "Requested to delete %s %s.\n"
	if len(deletedIds) == 1 {
		output.Printf(c.Config.EnableColor, deleteMsg, "Flink compute pool", fmt.Sprintf(`"%s"`, deletedIds[0]))
	} else if len(deletedIds) > 1 {
		output.Printf(c.Config.EnableColor, deleteMsg, plural.Plural("Flink compute pool"), utils.ArrayToCommaDelimitedString(deletedIds, "and"))
	}

	errs := multierror.Append(err, c.clearComputePoolsFromConfigIfDeleted(deletedIds))
	return errs.ErrorOrNil()
}

// clearComputePoolsFromConfigIfDeleted resets the login context's current Flink compute pool
// when it is among the just-deleted ids, so a context-scoped `describe` doesn't resolve a
// stale, deleted id (which would 404 instead of reporting "no Flink compute pool selected").
// General over context-selectable resources; the cosmetic per-Flink compute pool cache entry is
// intentionally left in place (see the create-side AddEnvironment omission).
func (c *computePoolCommand) clearComputePoolsFromConfigIfDeleted(deletedIds []string) error {
	errs := &multierror.Error{ErrorFormat: errors.CustomMultierrorList}
	for _, id := range deletedIds {
		if id == c.Context.GetCurrentFlinkComputePool() {
			errs = multierror.Append(errs, c.Context.SetCurrentFlinkComputePool(""), c.Config.Save())
		}
	}
	return errs.ErrorOrNil()
}
