// Code generated by cli-terraform-generator; DO NOT EDIT.

package flink

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	flinkv2 "github.com/confluentinc/ccloud-sdk-go-v2/flink/v2"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
	"github.com/confluentinc/cli/v4/pkg/output"
)

func (c *regionCommand) newUseCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "use",
		Short: "Use a Flink region in subsequent commands.",
		Long:  "Choose a Flink region to be used in subsequent commands which support passing a region with the `--region` flag.",
		Args:  cobra.NoArgs,
		RunE:  c.use,
	}

	pcmd.AddCloudFlag(cmd)
	pcmd.AddRegionFlagFlink(cmd, c.AuthenticatedCLICommand)

	cobra.CheckErr(cmd.MarkFlagRequired("cloud"))
	cobra.CheckErr(cmd.MarkFlagRequired("region"))

	return cmd
}

func (c *regionCommand) use(cmd *cobra.Command, _ []string) error {
	cloud, err := cmd.Flags().GetString("cloud")
	if err != nil {
		return err
	}

	region, err := cmd.Flags().GetString("region")
	if err != nil {
		return err
	}

	regions, err := c.V2Client.ListFlinkRegions(cloud, region)
	if err != nil {
		return err
	}
	var selected *flinkv2.FcpmV2Region
	for _, candidate := range regions {
		if candidate.GetCloud() == strings.ToUpper(cloud) && candidate.GetRegionName() == region {
			selected = &candidate
			break
		}
	}
	if selected == nil {
		return errors.NewErrorWithSuggestions(
			fmt.Sprintf("no Flink region found for cloud %q and region %q", cloud, region),
			"List available Flink regions with `confluent flink region list`.",
		)
	}

	// Scoped to the previous selection, so recording a new one clears it.
	output.Println(c.Config.EnableColor, "The current Flink endpoint has been unset due to the cloud or region change.")
	if err := c.Context.SetCurrentFlinkEndpoint(""); err != nil {
		return err
	}

	if err := c.Context.SetCurrentFlinkCloudProvider(cloud); err != nil {
		return err
	}

	if err := c.Context.SetCurrentFlinkRegion(region); err != nil {
		return err
	}

	if err := c.Config.Save(); err != nil {
		return err
	}

	output.Printf(c.Config.EnableColor, errors.UsingResourceMsg, "Flink region", selected.GetDisplayName())
	return nil
}
