// Code generated by cli-terraform-generator; DO NOT EDIT.

package flink

import (
	"github.com/spf13/cobra"

	"github.com/confluentinc/cli/v4/pkg/output"
)

func (c *regionCommand) newUnsetCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "unset",
		Short: "Unset the current Flink cloud and region.",
		Long:  "Unset the current Flink cloud and region that was set with the `use` command.",
		Args:  cobra.NoArgs,
		RunE:  c.unset,
	}

	return cmd
}

func (c *regionCommand) unset(_ *cobra.Command, _ []string) error {
	cloudToUnset := c.Context.GetCurrentFlinkCloudProvider()
	regionToUnset := c.Context.GetCurrentFlinkRegion()
	output.Println(c.Config.EnableColor, "Unset the current Flink cloud and region")

	if cloudToUnset == "" && regionToUnset == "" {
		return nil
	}
	if err := c.Context.SetCurrentFlinkCloudProvider(""); err != nil {
		return err
	}
	if err := c.Context.SetCurrentFlinkRegion(""); err != nil {
		return err
	}
	if err := c.Config.Save(); err != nil {
		return err
	}

	return nil
}
