// Code generated by cli-terraform-generator v0.7.3; DO NOT EDIT.

package flink

import (
	"fmt"
	"strings"
	"time"

	"github.com/spf13/cobra"

	flinkv2 "github.com/confluentinc/ccloud-sdk-go-v2/flink/v2"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
	"github.com/confluentinc/cli/v4/pkg/examples"
	"github.com/confluentinc/cli/v4/pkg/wait"
)

func (c *computePoolCommand) newCreateCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create <name>",
		Short: "Create a Flink compute pool.",
		Args:  cobra.ExactArgs(1),
		RunE:  c.create,
		Example: examples.BuildExampleString(
			examples.Example{
				Text: `Create Flink compute pool "my-compute-pool" in AWS with 5 CFUs.`,
				Code: "confluent flink compute-pool create my-compute-pool --cloud aws --region us-west-2 --max-cfu 5",
			},
		),
	}

	// Required flags
	pcmd.AddCloudFlag(cmd)
	pcmd.AddRegionFlagFlink(cmd, c.AuthenticatedCLICommand)
	cobra.CheckErr(cmd.MarkFlagRequired("cloud"))
	cobra.CheckErr(cmd.MarkFlagRequired("region"))

	// Optional flags
	cmd.Flags().Bool("default-pool", false, "Indicate whether the Flink compute pool is a default compute pool or not.")
	pcmd.AddEnvironmentFlag(cmd, c.AuthenticatedCLICommand)
	cmd.Flags().Int32("max-cfu", 5, "Maximum number of Confluent Flink Units (CFU).")
	pcmd.RegisterFlagCompletionFunc(cmd, "max-cfu", func(_ *cobra.Command, _ []string) []string { return []string{"5", "10", "20", "30", "40", "50"} })
	cmd.Flags().Bool("wait", false, "Wait for the Flink compute pool to reach a ready or failed state before returning.")
	cmd.Flags().Duration("timeout", time.Hour, "Maximum time to wait for the Flink compute pool to reach a ready or failed state when --wait is set (e.g., '30s', '5m', '2h').")

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *computePoolCommand) create(cmd *cobra.Command, args []string) error {
	name := args[0]

	spec := flinkv2.FcpmV2ComputePoolSpec{}
	createReq := flinkv2.FcpmV2ComputePool{}

	spec.DisplayName = flinkv2.PtrString(name)
	cloud, err := cmd.Flags().GetString("cloud")
	if err != nil {
		return err
	}
	cloud = strings.ToUpper(cloud)
	spec.Cloud = flinkv2.PtrString(cloud)

	defaultPool, err := cmd.Flags().GetBool("default-pool")
	if err != nil {
		return err
	}
	if defaultPool {
		spec.DefaultPool = flinkv2.PtrBool(defaultPool)
	}

	environmentId, err := c.Context.EnvironmentId()
	if err != nil {
		return err
	}
	spec.Environment = &flinkv2.GlobalObjectReference{Id: environmentId}

	maxCfu, err := cmd.Flags().GetInt32("max-cfu")
	if err != nil {
		return err
	}
	spec.MaxCfu = flinkv2.PtrInt32(maxCfu)

	region, err := cmd.Flags().GetString("region")
	if err != nil {
		return err
	}
	spec.Region = flinkv2.PtrString(region)

	createReq.Spec = &spec
	computePool, httpResp, err := c.V2Client.CreateFlinkComputePool(createReq)
	if err != nil {
		return errors.CatchCCloudV2Error(err, httpResp)
	}

	shouldWait, err := cmd.Flags().GetBool("wait")
	if err != nil {
		return err
	}
	if shouldWait {
		timeout, err := cmd.Flags().GetDuration("timeout")
		if err != nil {
			return err
		}
		// Re-fetch the resource via its describe endpoint until it leaves the
		// pending set. The lookup key matches the describe command's positional
		// arg — an id, topic_name, display_name, etc. (see PrimaryIdentifierGetter).
		waitKey := computePool.GetId()
		computePool, err = wait.PollPhases(cmd.Context(), wait.PhaseOptions[flinkv2.FcpmV2ComputePool]{
			Fetch: func() (flinkv2.FcpmV2ComputePool, error) {
				v, _, err := c.V2Client.GetFlinkComputePool(waitKey, environmentId)
				return v, err
			},
			Phase:         func(v flinkv2.FcpmV2ComputePool) string { return v.Status.GetPhase() },
			PendingPhases: []string{"PROVISIONING"},
			FailedPhases:  []string{"FAILED"},
			Delay:         5 * time.Second,
			PollInterval:  10 * time.Second,
			Timeout:       timeout,
		})
		if err != nil {
			// wait.ErrFailed / wait.ErrTimeout are package-level sentinels
			// returned directly from Poll, so == is the correct compare.
			switch err {
			case wait.ErrFailed:
				return errors.NewErrorWithSuggestions(
					fmt.Sprintf(`Flink compute pool "%s" entered failed phase %q`, waitKey, computePool.Status.GetPhase()),
					fmt.Sprintf("Inspect the Flink compute pool with `confluent flink compute-pool describe %s`.", waitKey),
				)
			case wait.ErrTimeout:
				return errors.NewErrorWithSuggestions(
					fmt.Sprintf(`wait timed out: Flink compute pool "%s" is still in phase %q`, waitKey, computePool.Status.GetPhase()),
					"Increase `--timeout` or omit `--wait`.",
				)
			default:
				return err
			}
		}
	}

	return c.printComputePool(cmd, computePool)
}
