// Code generated by cli-terraform-generator; DO NOT EDIT.

package testserver

import (
	"encoding/json"
	"net/http"
	"os"
	"path/filepath"
	"testing"

	"github.com/gorilla/mux"
	"github.com/stretchr/testify/require"

	notificationsv1 "github.com/confluentinc/ccloud-sdk-go-v2/notifications/v1"
)

// Handler for "/notifications/v1/subscriptions"
func handleNotificationsV1Subscriptions(t *testing.T) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodGet:
			subscription := readNotificationsV1SubscriptionFile(t, "read_created_subscription.json")

			subscriptionList := &notificationsv1.NotificationsV1SubscriptionList{
				Data: []notificationsv1.NotificationsV1Subscription{subscription},
			}

			err := json.NewEncoder(w).Encode(subscriptionList)
			require.NoError(t, err)
		case http.MethodPost:
			subscription := readNotificationsV1SubscriptionFile(t, "create_subscription.json")

			// Overwrite updated fields using the request body
			err := json.NewDecoder(r.Body).Decode(&subscription)
			require.NoError(t, err)

			err = json.NewEncoder(w).Encode(subscription)
			require.NoError(t, err)
		}
	}
}

// Handler for "/notifications/v1/subscriptions/{id}"
func handleNotificationsV1SubscriptionsId(t *testing.T) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		id := mux.Vars(r)["id"]
		switch r.Method {
		case http.MethodGet:
			switch id {
			case "invalid":
				w.WriteHeader(http.StatusNotFound)
			default:
				subscription := readNotificationsV1SubscriptionFile(t, "read_created_subscription.json")

				err := json.NewEncoder(w).Encode(&subscription)
				require.NoError(t, err)
			}
		case http.MethodPatch:
			switch id {
			case "invalid":
				w.WriteHeader(http.StatusNotFound)
			default:
				subscription := readNotificationsV1SubscriptionFile(t, "read_created_subscription.json")

				// Overwrite updated fields using the request body
				err := json.NewDecoder(r.Body).Decode(&subscription)
				require.NoError(t, err)

				err = json.NewEncoder(w).Encode(subscription)
				require.NoError(t, err)
			}
		case http.MethodDelete:
			switch id {
			case "invalid":
				w.WriteHeader(http.StatusNotFound)
			default:
				w.WriteHeader(http.StatusNoContent)
			}
		}
	}
}

func readNotificationsV1SubscriptionFile(t *testing.T, filename string) notificationsv1.NotificationsV1Subscription {
	jsonPath := filepath.Join("test", "fixtures", "input", "notifications", "subscription", filename)
	jsonData, err := os.ReadFile(jsonPath)
	require.NoError(t, err)

	subscription := notificationsv1.NotificationsV1Subscription{}
	err = json.Unmarshal(jsonData, &subscription)
	require.NoError(t, err)

	return subscription
}
