// Code generated by cli-terraform-generator; DO NOT EDIT.

package testserver

import (
	"encoding/json"
	"net/http"
	"os"
	"path/filepath"
	"testing"

	"github.com/gorilla/mux"
	"github.com/stretchr/testify/require"

	notificationsv1 "github.com/confluentinc/ccloud-sdk-go-v2/notifications/v1"
)

// Handler for "/notifications/v1/integrations"
func handleNotificationsV1Integrations(t *testing.T) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodGet:
			integration := readNotificationsV1IntegrationFile(t, "read_created_slack_target.json")

			integrationList := &notificationsv1.NotificationsV1IntegrationList{
				Data: []notificationsv1.NotificationsV1Integration{integration},
			}

			err := json.NewEncoder(w).Encode(integrationList)
			require.NoError(t, err)
		case http.MethodPost:
			integration := readNotificationsV1IntegrationFile(t, "create_slack_target.json")

			// Overwrite updated fields using the request body
			err := json.NewDecoder(r.Body).Decode(&integration)
			require.NoError(t, err)

			err = json.NewEncoder(w).Encode(integration)
			require.NoError(t, err)
		}
	}
}

// Handler for "/notifications/v1/integrations/{id}"
func handleNotificationsV1IntegrationsId(t *testing.T) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		id := mux.Vars(r)["id"]
		switch r.Method {
		case http.MethodGet:
			switch id {
			case "invalid":
				w.WriteHeader(http.StatusNotFound)
			default:
				integration := readNotificationsV1IntegrationFile(t, "read_created_slack_target.json")

				err := json.NewEncoder(w).Encode(&integration)
				require.NoError(t, err)
			}
		case http.MethodPatch:
			switch id {
			case "invalid":
				w.WriteHeader(http.StatusNotFound)
			default:
				integration := readNotificationsV1IntegrationFile(t, "read_created_slack_target.json")

				// Overwrite updated fields using the request body
				err := json.NewDecoder(r.Body).Decode(&integration)
				require.NoError(t, err)

				err = json.NewEncoder(w).Encode(integration)
				require.NoError(t, err)
			}
		case http.MethodDelete:
			switch id {
			case "invalid":
				w.WriteHeader(http.StatusNotFound)
			default:
				w.WriteHeader(http.StatusNoContent)
			}
		}
	}
}

func readNotificationsV1IntegrationFile(t *testing.T, filename string) notificationsv1.NotificationsV1Integration {
	jsonPath := filepath.Join("test", "fixtures", "input", "notifications", "integration", filename)
	jsonData, err := os.ReadFile(jsonPath)
	require.NoError(t, err)

	integration := notificationsv1.NotificationsV1Integration{}
	err = json.Unmarshal(jsonData, &integration)
	require.NoError(t, err)

	return integration
}
