// Code generated by cli-terraform-generator v0.8.4; DO NOT EDIT.

package notifications

import (
	"strings"

	"github.com/spf13/cobra"

	notificationsv1 "github.com/confluentinc/ccloud-sdk-go-v2/notifications/v1"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
)

func (c *subscriptionCommand) newCreateCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a notifications subscription.",
		Args:  cobra.NoArgs,
		RunE:  c.create,
	}

	// Required flags
	cmd.Flags().String("notification-type", "", "The type of notification to subscribe to.")
	cmd.Flags().StringSlice("integrations", nil, "A comma-separated list of integration IDs to notify.")
	cobra.CheckErr(cmd.MarkFlagRequired("integrations"))
	cobra.CheckErr(cmd.MarkFlagRequired("notification-type"))

	// Optional flags
	cmd.Flags().String("current-state", "", "Denotes the state of the subscription. When the subscription is ENABLED, the user will receive notification on the configured integrations. If the subscription is DISABLED, the user will not receive any notification for the configured notification type. Note that, you cannot disable a subscription for `REQUIRED` notification type.")
	pcmd.RegisterFlagCompletionFunc(cmd, "current-state", func(_ *cobra.Command, _ []string) []string { return []string{"ENABLED", "DISABLED"} })

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *subscriptionCommand) create(cmd *cobra.Command, args []string) error {
	createReq := notificationsv1.NotificationsV1Subscription{}

	currentState, err := cmd.Flags().GetString("current-state")
	if err != nil {
		return err
	}
	currentState = strings.ToUpper(currentState)
	if currentState != "" {
		createReq.CurrentState = notificationsv1.PtrString(currentState)
	}

	notificationTypeId, err := cmd.Flags().GetString("notification-type")
	if err != nil {
		return err
	}
	createReq.NotificationType = &notificationsv1.GlobalObjectReference{Id: notificationTypeId, Related: "https://confluent.cloud/_", ResourceName: "https://confluent.cloud/_"}

	integrations, err := cmd.Flags().GetStringSlice("integrations")
	if err != nil {
		return err
	}
	integrationsRefs := make([]notificationsv1.GlobalObjectReference, len(integrations))
	for i, id := range integrations {
		integrationsRefs[i] = notificationsv1.GlobalObjectReference{Id: id, Related: "https://confluent.cloud/_", ResourceName: "https://confluent.cloud/_"}
	}
	createReq.Integrations = &integrationsRefs

	subscription, httpResp, err := c.V2Client.CreateNotificationsSubscription(createReq)
	if err != nil {
		return errors.CatchCCloudV2Error(err, httpResp)
	}

	return printSubscription(cmd, subscription)
}
