// Code generated by cli-terraform-generator; DO NOT EDIT.

package notifications

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/deletion"
)

func (c *resourcePreferenceCommand) newDeleteCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id-1> [id-2] ... [id-n]",
		Short: "Delete one or more notifications resource preferences.",
		Args:  cobra.MinimumNArgs(1),
		RunE:  c.delete,
	}

	// Required flags

	// Optional flags

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddForceFlag(cmd)

	return cmd
}

func (c *resourcePreferenceCommand) delete(cmd *cobra.Command, args []string) error {
	existenceFunc := func(primaryId string) bool {
		_, _, err := c.V2Client.GetNotificationsResourcePreference(primaryId)
		return err == nil
	}

	if err := deletion.ValidateAndConfirm(cmd, args, existenceFunc, "notifications resource preference"); err != nil {
		return err
	}

	deleteFunc := func(primaryId string) error {
		return c.V2Client.DeleteNotificationsResourcePreference(primaryId)
	}

	_, err := deletion.Delete(cmd, args, deleteFunc, "notifications resource preference")
	return err
}
