// Code generated by cli-terraform-generator; DO NOT EDIT.

package notifications

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/output"
)

func (c *integrationCommand) newListCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List notifications integrations.",
		Args:  cobra.NoArgs,
		RunE:  c.list,
	}

	// Required flags

	// Optional flags

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *integrationCommand) list(cmd *cobra.Command, _ []string) error {
	integrations, err := c.V2Client.ListNotificationsIntegrations()
	if err != nil {
		return err
	}

	list := output.NewList(cmd)
	for _, integration := range integrations {
		out := &integrationOut{
			ID:          integration.GetId(),
			DisplayName: integration.GetDisplayName(),
			Description: integration.GetDescription(),
		}
		if integration.Target.NotificationsV1SlackTarget != nil {
			out.SlackTargetWebhookUrl = integration.Target.NotificationsV1SlackTarget.GetWebhookUrl()
		}
		if integration.Target.NotificationsV1RoleEmailTarget != nil {
			out.RoleEmailTargetRoleName = integration.Target.NotificationsV1RoleEmailTarget.GetRoleName()
		}
		if integration.Target.NotificationsV1WebhookTarget != nil {
			out.WebhookTargetUrl = integration.Target.NotificationsV1WebhookTarget.GetUrl()
		}
		if integration.Target.NotificationsV1MsTeamsTarget != nil {
			out.MsTeamsTargetWebhookUrl = integration.Target.NotificationsV1MsTeamsTarget.GetWebhookUrl()
		}
		list.Add(out)
	}
	return list.Print()
}
