// Code generated by cli-terraform-generator; DO NOT EDIT.

package notifications

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/config"
)

func New(cfg *config.Config, prerunner pcmd.PreRunner) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "notifications",
		Short: "Manage Cloud Notifications.",
	}

	cmd.AddCommand(
		newIntegrationCommand(cfg, prerunner),
		newNotificationTypeCommand(cfg, prerunner),
		newResourcePreferenceCommand(cfg, prerunner),
		newResourceSubscriptionCommand(cfg, prerunner),
		newSubscriptionCommand(cfg, prerunner),
		newUserNotificationCommand(cfg, prerunner),
		// cli-tfgen:cli-subcommands
	)

	return cmd
}
