// Code generated by cli-terraform-generator; DO NOT EDIT.

package notifications

import (
	"strings"

	"github.com/spf13/cobra"

	notificationsv1 "github.com/confluentinc/ccloud-sdk-go-v2-internal/notifications/v1"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
)

func (c *resourceSubscriptionCommand) newCreateCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a notifications resource subscription.",
		Args:  cobra.NoArgs,
		RunE:  c.create,
	}

	// Required flags
	cmd.Flags().String("resource", "", "Denotes the Confluent Cloud resource definition.")
	cmd.Flags().String("resource-type", "", "Denotes the Confluent Cloud resource type.")
	pcmd.RegisterFlagCompletionFunc(cmd, "resource-type", func(_ *cobra.Command, _ []string) []string {
		return []string{"ENVIRONMENT", "CLUSTER", "CONNECTOR", "FLINK_COMPUTE_POOL", "FLINK_STATEMENT"}
	})
	cmd.Flags().String("notification-type", "", "The type of notification to subscribe to.")
	cmd.Flags().StringSlice("integrations", nil, "Integrations to which notifications are to be sent.")
	cobra.CheckErr(cmd.MarkFlagRequired("integrations"))
	cobra.CheckErr(cmd.MarkFlagRequired("notification-type"))
	cobra.CheckErr(cmd.MarkFlagRequired("resource"))
	cobra.CheckErr(cmd.MarkFlagRequired("resource-type"))

	// Optional flags
	cmd.Flags().String("current-state", "", "Denotes the state of the resource preference. When the resource preference is ENABLED, the user will receive notifications for the Confluent Cloud resource. If the resource preference is DISABLED, the user will not receive any notification for the resource. Note that, you will still receive notifications for `REQUIRED` notification type even when it is DISABLED.")
	pcmd.RegisterFlagCompletionFunc(cmd, "current-state", func(_ *cobra.Command, _ []string) []string { return []string{"ENABLED", "DISABLED"} })

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *resourceSubscriptionCommand) create(cmd *cobra.Command, args []string) error {
	createReq := notificationsv1.NotificationsV1ResourceSubscription{}

	resource, err := cmd.Flags().GetString("resource")
	if err != nil {
		return err
	}
	createReq.Resource = notificationsv1.PtrString(resource)

	resourceType, err := cmd.Flags().GetString("resource-type")
	if err != nil {
		return err
	}
	resourceType = strings.ToUpper(resourceType)
	createReq.ResourceType = notificationsv1.PtrString(resourceType)

	currentState, err := cmd.Flags().GetString("current-state")
	if err != nil {
		return err
	}
	currentState = strings.ToUpper(currentState)
	if currentState != "" {
		createReq.CurrentState = notificationsv1.PtrString(currentState)
	}

	notificationTypeId, err := cmd.Flags().GetString("notification-type")
	if err != nil {
		return err
	}
	createReq.NotificationType = &notificationsv1.GlobalObjectReference{Id: notificationTypeId}

	integrations, err := cmd.Flags().GetStringSlice("integrations")
	if err != nil {
		return err
	}
	integrationsRefs := make([]notificationsv1.GlobalObjectReference, len(integrations))
	for i, id := range integrations {
		integrationsRefs[i] = notificationsv1.GlobalObjectReference{Id: id}
	}
	createReq.Integrations = &integrationsRefs

	resourceSubscription, httpResp, err := c.V2Client.CreateNotificationsResourceSubscription(createReq)
	if err != nil {
		return errors.CatchCCloudV2Error(err, httpResp)
	}

	return printResourceSubscription(cmd, resourceSubscription)
}
