// Code generated by cli-terraform-generator; DO NOT EDIT.

package notifications

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
)

func (c *resourcePreferenceCommand) newDescribeCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "describe <id>",
		Short: "Describe a notifications resource preference.",
		Args:  cobra.ExactArgs(1),
		RunE:  c.describe,
	}

	// Required flags

	// Optional flags

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *resourcePreferenceCommand) describe(cmd *cobra.Command, args []string) error {
	id := args[0]

	resourcePreference, httpResp, err := c.V2Client.GetNotificationsResourcePreference(id)
	if err != nil {
		return errors.CatchCCloudV2Error(err, httpResp)
	}

	return printResourcePreference(cmd, resourcePreference)
}
