// Code generated by cli-terraform-generator; DO NOT EDIT.

package notifications

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	notificationsv1 "github.com/confluentinc/ccloud-sdk-go-v2-internal/notifications/v1"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
	"github.com/confluentinc/cli/v4/pkg/output"
)

func (c *integrationCommand) newUpdateCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "update <id>",
		Short:             "Update an existing notifications integration.",
		Args:              cobra.ExactArgs(1),
		ValidArgsFunction: pcmd.NewValidArgsFunction(c.validArgs),
		RunE:              c.update,
	}

	// Required flags

	// Optional flags
	cmd.Flags().String("kind", "", "Integration-specific details (integration targets). One of: Slack, Webhook, MsTeams.")
	cmd.Flags().String("webhook-url", "", "Slack: Slack Webhook URL for the particular Slack channel. MsTeams: MS Teams Webhook URL for the particular team channel.")
	cmd.Flags().String("url", "", "URL endpoint for the webhook.")
	cmd.Flags().String("display-name", "", "A human readable name for the particular integration.")
	cmd.Flags().String("description", "", "A human readable description for the particular integration.")

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *integrationCommand) update(cmd *cobra.Command, args []string) error {
	id := args[0]

	updateReq := notificationsv1.NotificationsV1Integration{}

	if cmd.Flags().Changed("display-name") {
		displayName, err := cmd.Flags().GetString("display-name")
		if err != nil {
			return err
		}
		updateReq.DisplayName = notificationsv1.PtrString(displayName)
	}

	if cmd.Flags().Changed("description") {
		description, err := cmd.Flags().GetString("description")
		if err != nil {
			return err
		}
		updateReq.Description = notificationsv1.PtrString(description)
	}

	// oneOf: target
	kind, err := cmd.Flags().GetString("kind")
	if err != nil {
		return err
	}
	if !cmd.Flags().Changed("kind") {
		for _, flag := range []string{"webhook-url", "url"} {
			if cmd.Flags().Changed(flag) {
				return fmt.Errorf("--%s requires --kind", flag)
			}
		}
	}
	if cmd.Flags().Changed("kind") {

		switch strings.ToLower(kind) {
		case "slack":
			slackTarget := notificationsv1.NotificationsV1SlackTarget{
				Kind: "Slack",
			}
			webhookUrl, err := cmd.Flags().GetString("webhook-url")
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("webhook-url") {
				slackTarget.WebhookUrl = webhookUrl
			}
			slackTargetOneOf := notificationsv1.NotificationsV1SlackTargetAsNotificationsV1Target(&slackTarget)
			updateReq.Target = &slackTargetOneOf
		case "webhook":
			webhookTarget := notificationsv1.NotificationsV1WebhookTarget{
				Kind: "Webhook",
			}
			url, err := cmd.Flags().GetString("url")
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("url") {
				webhookTarget.Url = url
			}
			webhookTargetOneOf := notificationsv1.NotificationsV1WebhookTargetAsNotificationsV1Target(&webhookTarget)
			updateReq.Target = &webhookTargetOneOf
		case "msteams":
			msTeamsTarget := notificationsv1.NotificationsV1MsTeamsTarget{
				Kind: "MsTeams",
			}
			webhookUrl, err := cmd.Flags().GetString("webhook-url")
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("webhook-url") {
				msTeamsTarget.WebhookUrl = webhookUrl
			}
			msTeamsTargetOneOf := notificationsv1.NotificationsV1MsTeamsTargetAsNotificationsV1Target(&msTeamsTarget)
			updateReq.Target = &msTeamsTargetOneOf
		default:
			return fmt.Errorf("unrecognized target type: %s", kind)
		}
	}
	integration, httpResp, err := c.V2Client.UpdateNotificationsIntegration(id, updateReq)
	if err != nil {
		return errors.CatchCCloudV2Error(err, httpResp)
	}

	if output.GetFormat(cmd) == output.Human {
		output.Printf(c.Config.EnableColor, "Updated notifications integration \"%s\".\n", id)
	}
	return printIntegration(cmd, integration)
}
