// Code generated by cli-terraform-generator; DO NOT EDIT.

package notifications

import (
	"github.com/spf13/cobra"

	notificationsv1 "github.com/confluentinc/ccloud-sdk-go-v2-internal/notifications/v1"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
	"github.com/confluentinc/cli/v4/pkg/output"
)

func (c *userNotificationCommand) newUpdateCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "update <id>",
		Short:             "Update an existing notifications user notification.",
		Args:              cobra.ExactArgs(1),
		ValidArgsFunction: pcmd.NewValidArgsFunction(c.validArgs),
		RunE:              c.update,
	}

	// Required flags

	// Optional flags
	cmd.Flags().Bool("read", false, "Whether the notification has been read by the user.")

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *userNotificationCommand) update(cmd *cobra.Command, args []string) error {
	id := args[0]

	updateReq := notificationsv1.NotificationsV1UserNotification{}

	if cmd.Flags().Changed("read") {
		read, err := cmd.Flags().GetBool("read")
		if err != nil {
			return err
		}
		updateReq.Read = notificationsv1.PtrBool(read)
	}

	userNotification, httpResp, err := c.V2Client.UpdateNotificationsUserNotification(id, updateReq)
	if err != nil {
		return errors.CatchCCloudV2Error(err, httpResp)
	}

	if output.GetFormat(cmd) == output.Human {
		output.Printf(c.Config.EnableColor, "Updated notifications user notification \"%s\".\n", id)
	}
	return printUserNotification(cmd, userNotification)
}
