// Code generated by cli-terraform-generator; DO NOT EDIT.

package notifications

import (
	"fmt"

	"github.com/spf13/cobra"

	notificationsv1 "github.com/confluentinc/ccloud-sdk-go-v2-internal/notifications/v1"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/config"
	"github.com/confluentinc/cli/v4/pkg/output"
)

type notificationTypeCommand struct {
	*pcmd.AuthenticatedCLICommand
}

type notificationTypeOut struct {
	ID                   string `human:"ID" serialized:"id"`
	DisplayName          string `human:"Display Name" serialized:"display_name"`
	Category             string `human:"Category" serialized:"category"`
	Description          string `human:"Description" serialized:"description"`
	SubscriptionPriority string `human:"Subscription Priority" serialized:"subscription_priority"`
	IsIncludedInPlan     bool   `human:"Is Included In Plan" serialized:"is_included_in_plan"`
	Severity             string `human:"Severity" serialized:"severity"`
}

func newNotificationTypeCommand(cfg *config.Config, prerunner pcmd.PreRunner) *cobra.Command { //nolint:unparam
	cmd := &cobra.Command{
		Use:         "notification-type",
		Short:       "Manage Confluent Cloud notifications notification types.",
		Annotations: map[string]string{pcmd.RunRequirement: pcmd.RequireNonAPIKeyCloudLogin},
	}

	c := &notificationTypeCommand{
		AuthenticatedCLICommand: pcmd.NewAuthenticatedCLICommand(cmd, prerunner),
	}

	cmd.AddCommand(
		c.newDescribeCommand(),
		c.newListCommand(),
	)

	return cmd
}

func printNotificationType(cmd *cobra.Command, notificationType notificationsv1.NotificationsV1NotificationType) error {
	table := output.NewTable(cmd)
	out := &notificationTypeOut{
		ID:                   notificationType.GetId(),
		DisplayName:          notificationType.GetDisplayName(),
		Category:             notificationType.GetCategory(),
		Description:          notificationType.GetDescription(),
		SubscriptionPriority: notificationType.GetSubscriptionPriority(),
		IsIncludedInPlan:     notificationType.GetIsIncludedInPlan(),
		Severity:             notificationType.GetSeverity(),
	}
	table.Add(out)
	return table.Print()
}

func (c *notificationTypeCommand) validArgs(cmd *cobra.Command, args []string) []string {
	if len(args) > 0 {
		return nil
	}

	return c.validArgsMultiple(cmd, args)
}

func (c *notificationTypeCommand) validArgsMultiple(cmd *cobra.Command, args []string) []string {
	if err := c.PersistentPreRunE(cmd, args); err != nil {
		return nil
	}

	return c.autocompleteNotificationTypes()
}

func (c *notificationTypeCommand) autocompleteNotificationTypes() []string {
	notificationTypes, err := c.V2Client.ListNotificationsNotificationTypes("")
	if err != nil {
		return nil
	}

	suggestions := make([]string, len(notificationTypes))
	for i, notificationType := range notificationTypes {
		suggestions[i] = fmt.Sprintf("%s\t%s", notificationType.GetId(), notificationType.GetDisplayName())
	}
	return suggestions
}
