// Code generated by cli-terraform-generator; DO NOT EDIT.

package organization

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/output"
)

func (c *organizationCommand) newListCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List organizations.",
		Args:  cobra.NoArgs,
		RunE:  c.list,
	}

	// Required flags

	// Optional flags

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *organizationCommand) list(cmd *cobra.Command, _ []string) error {
	organizations, err := c.V2Client.ListOrgOrganizations()
	if err != nil {
		return err
	}

	list := output.NewList(cmd)
	for _, organization := range organizations {
		out := &organizationOut{
			IsCurrent:  organization.GetId() == c.Context.GetCurrentOrganization(),
			ID:         organization.GetId(),
			Name:       organization.GetDisplayName(),
			JitEnabled: organization.GetJitEnabled(),
		}
		list.Add(out)
	}
	return list.Print()
}
