// Code generated by cli-terraform-generator; DO NOT EDIT.

package organization

import (
	"github.com/spf13/cobra"

	orgv2 "github.com/confluentinc/ccloud-sdk-go-v2/org/v2"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
)

func (c *scimTokenCommand) newCreateCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create an Organization scim token.",
		Args:  cobra.NoArgs,
		RunE:  c.create,
	}

	// Required flags

	// Optional flags
	cmd.Flags().Int32("expire-duration-mins", 0, "The duration in minutes after which the token expires. Defaults to 6 months (259200 minutes) if not specified. Minimum: 1 month (43200 minutes). Maximum: 2 years (1051200 minutes).")

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *scimTokenCommand) create(cmd *cobra.Command, args []string) error {
	createReq := orgv2.InlineObject{}

	expireDurationMins, err := cmd.Flags().GetInt32("expire-duration-mins")
	if err != nil {
		return err
	}
	if expireDurationMins != 0 {
		createReq.ExpireDurationMins = orgv2.PtrInt32(expireDurationMins)
	}

	scimToken, httpResp, err := c.V2Client.CreateOrgScimToken(createReq)
	if err != nil {
		return errors.CatchCCloudV2Error(err, httpResp)
	}

	return printScimToken(cmd, scimToken)
}
