FROM --platform=linux/amd64 centos:7

RUN yum -y update

RUN yum -y install sudo make gcc gcc-c++

RUN sudo yum -y install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm && \
    sudo yum -y install git wget
    
RUN mkdir -p /cli
