FROM --platform=linux/amd64 050879227952.dkr.ecr.us-west-1.amazonaws.com/confluentinc/cli-centos-base-amd64:latest

COPY . /cli/

RUN export GO_VERSION=$(cat /cli/.go-version) && \
    wget "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz" && \
    sudo tar -C /usr/local -xzf "go${GO_VERSION}.linux-amd64.tar.gz"

ENV PATH=${PATH}:/usr/local/go/bin:/root/go/bin

RUN cd /cli && make gorelease-linux-amd64

# Install Node.js
RUN curl -sL https://rpm.nodesource.com/setup_14.x | bash -
RUN yum install -y nodejs

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install server dependencies
RUN npm install

# Copy the WebSocket server code to the container
COPY docker/server.js ./

# Expose the port on which the WebSocket server will run (e.g., 8080)
EXPOSE 8080

# Start the WebSocket server when the container starts
CMD ["node", "server.js", "&"]

RUN cd /cli && for file in prebuilt/*.txt; do mv -v "$file" "${file/checksums/checksums_linux}"; done;
