FROM --platform=linux/amd64 ubuntu:20.04

ARG IS_TEST="true"

SHELL ["/bin/bash", "-c"]

RUN apt -y update

RUN apt -y install make git wget musl-tools curl

RUN curl -O -L "https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign_2.2.4_amd64.deb"

RUN dpkg -i cosign_2.2.4_amd64.deb

COPY . /cli/

RUN export GO_VERSION=$(cat /cli/.go-version) && \
    wget "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz" && \
    tar -C /usr/local -xzf "go${GO_VERSION}.linux-amd64.tar.gz"

ENV PATH=${PATH}:/usr/local/go/bin:/root/go/bin

RUN cd /cli/ && \
    CC=musl-gcc CGO_LDFLAGS="-static" CGO_ENABLED=1 GOEXPERIMENT=boringcrypto go build -tags musl -ldflags="-s -w -X main.commit="00000000" -X main.date="1970-01-01T00:00:00Z" -X main.isTest=${IS_TEST}" ./cmd/confluent
