// Code generated by cli-terraform-generator v0.8.1; DO NOT EDIT.

package usm

import (
	"strings"

	"github.com/spf13/cobra"

	usmv1 "github.com/confluentinc/ccloud-sdk-go-v2/usm/v1"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
	"github.com/confluentinc/cli/v4/pkg/examples"
)

func (c *kafkaClusterCommand) newCreateCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:     "register <confluent-platform-kafka-cluster-id>",
		Short:   "Register a USM Kafka cluster.",
		Args:    cobra.ExactArgs(1),
		Aliases: []string{"create"},
		RunE:    c.create,
		Example: examples.BuildExampleString(
			examples.Example{
				Text: "Register a Confluent Platform Kafka cluster with the ID 4k0R9d1GTS5tI9f4Y2xZ0Q.",
				Code: "confluent usm kafka-cluster register 4k0R9d1GTS5tI9f4Y2xZ0Q --name my-kafka-cluster --cloud aws --region us-east-1",
			},
		),
	}

	// Required flags
	cmd.Flags().String("name", "", "A human-readable name for the Confluent Platform Kafka cluster.")
	pcmd.AddCloudFlag(cmd)
	cmd.Flags().String("region", "", "The home region of the Confluent Platform Kafka cluster where the metadata should be stored.")
	cobra.CheckErr(cmd.MarkFlagRequired("cloud"))
	cobra.CheckErr(cmd.MarkFlagRequired("name"))
	cobra.CheckErr(cmd.MarkFlagRequired("region"))

	// Optional flags
	pcmd.AddEnvironmentFlag(cmd, c.AuthenticatedCLICommand)

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *kafkaClusterCommand) create(cmd *cobra.Command, args []string) error {
	arg := args[0]

	createReq := usmv1.UsmV1KafkaCluster{}

	createReq.ConfluentPlatformKafkaClusterId = usmv1.PtrString(arg)
	displayName, err := cmd.Flags().GetString("name")
	if err != nil {
		return err
	}
	createReq.DisplayName = usmv1.PtrString(displayName)

	cloud, err := cmd.Flags().GetString("cloud")
	if err != nil {
		return err
	}
	cloud = strings.ToUpper(cloud)
	createReq.Cloud = usmv1.PtrString(cloud)

	region, err := cmd.Flags().GetString("region")
	if err != nil {
		return err
	}
	createReq.Region = usmv1.PtrString(region)

	environmentId, err := c.Context.EnvironmentId()
	if err != nil {
		return err
	}
	createReq.Environment = &usmv1.EnvScopedObjectReference{Id: environmentId}

	kafkaCluster, httpResp, err := c.V2Client.CreateUsmKafkaCluster(createReq)
	if err != nil {
		return errors.CatchCCloudV2Error(err, httpResp)
	}

	return printKafkaCluster(cmd, kafkaCluster)
}
