// Code generated by cli-terraform-generator v0.8.1; DO NOT EDIT.

package usm

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
	"github.com/confluentinc/cli/v4/pkg/examples"
)

func (c *kafkaClusterCommand) newDescribeCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "describe <id>",
		Short:             "Describe a USM Kafka cluster.",
		Args:              cobra.ExactArgs(1),
		ValidArgsFunction: pcmd.NewValidArgsFunction(c.validArgs),
		RunE:              c.describe,
		Example: examples.BuildExampleString(
			examples.Example{
				Text: "Describe a Confluent Platform Kafka cluster with the ID usmkc-abc123.",
				Code: "confluent usm kafka-cluster describe usmkc-abc123",
			},
		),
	}

	// Required flags

	// Optional flags
	pcmd.AddEnvironmentFlag(cmd, c.AuthenticatedCLICommand)

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *kafkaClusterCommand) describe(cmd *cobra.Command, args []string) error {
	id := args[0]
	environmentId, err := c.Context.EnvironmentId()
	if err != nil {
		return err
	}

	kafkaCluster, httpResp, err := c.V2Client.GetUsmKafkaCluster(id, environmentId)
	if err != nil {
		return errors.CatchCCloudV2Error(err, httpResp)
	}

	return printKafkaCluster(cmd, kafkaCluster)
}
