// Code generated by cli-terraform-generator; DO NOT EDIT.

package usm

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/config"
)

func New(cfg *config.Config, prerunner pcmd.PreRunner) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "usm",
		Aliases: []string{"unified-stream-manager"},
		Short:   "Manage Unified Stream Manager(USM).",
	}

	cmd.AddCommand(
		newKafkaClusterCommand(cfg, prerunner),
		// cli-tfgen:cli-subcommands
	)

	return cmd
}
