// Code generated by cli-terraform-generator; DO NOT EDIT.

package environment

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
	"github.com/confluentinc/cli/v4/pkg/output"
)

func (c *environmentCommand) newUseCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "use <id>",
		Short:             "Use an environment in subsequent commands.",
		Long:              "Choose the active Confluent Cloud environment for subsequent commands that accept the `--environment` flag.",
		Args:              cobra.ExactArgs(1),
		ValidArgsFunction: pcmd.NewValidArgsFunction(c.validArgs),
		RunE:              c.use,
	}

	return cmd
}

func (c *environmentCommand) use(_ *cobra.Command, args []string) error {
	id := args[0]

	if _, httpResp, err := c.V2Client.GetOrgEnvironment(id); err != nil {
		return errors.NewErrorWithSuggestions(
			errors.CatchCCloudV2Error(err, httpResp).Error(),
			"List available environments with `confluent environment list`.",
		)
	}

	c.Context.SetCurrentEnvironment(id)
	if err := c.Config.Save(); err != nil {
		return err
	}

	output.Printf(c.Config.EnableColor, errors.UsingResourceMsg, "environment", id)
	return nil
}
