// Code generated by cli-terraform-generator; DO NOT EDIT.

package environment

import (
	"fmt"

	"github.com/spf13/cobra"

	orgv2 "github.com/confluentinc/ccloud-sdk-go-v2/org/v2"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/config"
	"github.com/confluentinc/cli/v4/pkg/output"
)

type environmentCommand struct {
	*pcmd.AuthenticatedCLICommand
}

type environmentOut struct {
	IsCurrent               bool   `human:"Current" serialized:"is_current"`
	ID                      string `human:"ID" serialized:"id"`
	Name                    string `human:"Name" serialized:"name"`
	StreamGovernancePackage string `human:"Stream Governance Package" serialized:"stream_governance_package"`
}

func New(cfg *config.Config, prerunner pcmd.PreRunner) *cobra.Command { //nolint:unparam
	cmd := &cobra.Command{
		Use:         "environment",
		Aliases:     []string{"env"},
		Short:       "Manage and select Confluent Cloud environments.",
		Annotations: map[string]string{pcmd.RunRequirement: pcmd.RequireNonAPIKeyCloudLogin},
	}

	c := &environmentCommand{
		AuthenticatedCLICommand: pcmd.NewAuthenticatedCLICommand(cmd, prerunner),
	}

	cmd.AddCommand(
		c.newCreateCommand(),
		c.newDeleteCommand(),
		c.newDescribeCommand(),
		c.newListCommand(),
		c.newUpdateCommand(),
		c.newUseCommand(),
		// cli-tfgen:cli-subcommands
	)

	return cmd
}

func (c *environmentCommand) printEnvironment(cmd *cobra.Command, environment orgv2.OrgV2Environment) error {
	table := output.NewTable(cmd)
	out := &environmentOut{
		IsCurrent:               environment.GetId() == c.Context.GetCurrentEnvironment(),
		ID:                      environment.GetId(),
		Name:                    environment.GetDisplayName(),
		StreamGovernancePackage: environment.StreamGovernanceConfig.GetPackage(),
	}
	table.Add(out)
	return table.Print()
}

func (c *environmentCommand) validArgs(cmd *cobra.Command, args []string) []string {
	if len(args) > 0 {
		return nil
	}

	return c.validArgsMultiple(cmd, args)
}

func (c *environmentCommand) validArgsMultiple(cmd *cobra.Command, args []string) []string {
	if err := c.PersistentPreRunE(cmd, args); err != nil {
		return nil
	}

	return c.autocompleteEnvironments()
}

func (c *environmentCommand) autocompleteEnvironments() []string {
	environments, err := c.V2Client.ListOrgEnvironments()
	if err != nil {
		return nil
	}

	suggestions := make([]string, len(environments))
	for i, environment := range environments {
		suggestions[i] = fmt.Sprintf("%s\t%s", environment.GetId(), environment.GetDisplayName())
	}
	return suggestions
}
