// Code generated by cli-terraform-generator; DO NOT EDIT.

package environment

import (
	"strings"

	"github.com/spf13/cobra"

	orgv2 "github.com/confluentinc/ccloud-sdk-go-v2/org/v2"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
	"github.com/confluentinc/cli/v4/pkg/output"
)

func (c *environmentCommand) newUpdateCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "update <id>",
		Short:             "Update an existing environment.",
		Args:              cobra.ExactArgs(1),
		ValidArgsFunction: pcmd.NewValidArgsFunction(c.validArgs),
		RunE:              c.update,
	}

	// Required flags

	// Optional flags
	cmd.Flags().String("governance-package", "", "Specify the Stream Governance package as \"essentials\" or \"advanced\". On create, if not specified, the \"essentials\" package is used. Downgrading the package from \"advanced\" to \"essentials\" is not allowed once the Schema Registry cluster is provisioned.")
	cmd.Flags().String("name", "", "A human-readable name for the Environment.")

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *environmentCommand) update(cmd *cobra.Command, args []string) error {
	id := args[0]

	updateReq := orgv2.OrgV2Environment{}

	displayName, err := cmd.Flags().GetString("name")
	if err != nil {
		return err
	}
	if displayName != "" {
		updateReq.DisplayName = orgv2.PtrString(displayName)
	}

	// allOf: stream_governance_config
	governancePackage, err := cmd.Flags().GetString("governance-package")
	if err != nil {
		return err
	}
	if governancePackage != "" {
		updateReq.SetStreamGovernanceConfig(orgv2.OrgV2StreamGovernanceConfig{
			Package: strings.ToUpper(governancePackage),
		})
	}
	environment, httpResp, err := c.V2Client.UpdateOrgEnvironment(id, updateReq)
	if err != nil {
		return errors.CatchCCloudV2Error(err, httpResp)
	}

	if output.GetFormat(cmd) == output.Human {
		output.Printf(c.Config.EnableColor, "Updated environment \"%s\".\n", id)
	}
	return c.printEnvironment(cmd, environment)
}
