// Code generated by cli-terraform-generator; DO NOT EDIT.

package environment

import (
	"strings"

	"github.com/spf13/cobra"

	orgv2 "github.com/confluentinc/ccloud-sdk-go-v2/org/v2"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
)

func (c *environmentCommand) newCreateCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create <name>",
		Short: "Create an environment.",
		Args:  cobra.ExactArgs(1),
		RunE:  c.create,
	}

	// Required flags

	// Optional flags
	cmd.Flags().String("governance-package", "", "Specify the Stream Governance package as \"essentials\" or \"advanced\". On create, if not specified, the \"essentials\" package is used. Downgrading the package from \"advanced\" to \"essentials\" is not allowed once the Schema Registry cluster is provisioned.")

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *environmentCommand) create(cmd *cobra.Command, args []string) error {
	name := args[0]

	createReq := orgv2.OrgV2Environment{}

	createReq.DisplayName = orgv2.PtrString(name)
	// allOf: stream_governance_config
	governancePackage, err := cmd.Flags().GetString("governance-package")
	if err != nil {
		return err
	}
	if governancePackage != "" {
		createReq.SetStreamGovernanceConfig(orgv2.OrgV2StreamGovernanceConfig{
			Package: strings.ToUpper(governancePackage),
		})
	}
	environment, httpResp, err := c.V2Client.CreateOrgEnvironment(createReq)
	if err != nil {
		return errors.CatchCCloudV2Error(err, httpResp)
	}

	return c.printEnvironment(cmd, environment)
}
