// Code generated by cli-terraform-generator v1.0.0; DO NOT EDIT.

package environment

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
)

func (c *environmentCommand) newDescribeCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "describe [id]",
		Short:             "Describe an environment.",
		Args:              cobra.MaximumNArgs(1),
		ValidArgsFunction: pcmd.NewValidArgsFunction(c.validArgs),
		RunE:              c.describe,
	}

	// Required flags

	// Optional flags

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *environmentCommand) describe(cmd *cobra.Command, args []string) error {
	id := c.Context.GetCurrentEnvironment()
	if len(args) > 0 {
		id = args[0]
	}
	if id == "" {
		return errors.NewErrorWithSuggestions(
			"no environment selected",
			"Select an environment with `confluent environment use` or as an argument.",
		)
	}

	environment, httpResp, err := c.V2Client.GetOrgEnvironment(id)
	if err != nil {
		return errors.NewErrorWithSuggestions(
			errors.CatchCCloudV2Error(err, httpResp).Error(),
			"List available environments with `confluent environment list`.",
		)
	}

	return c.printEnvironment(cmd, environment)
}
