FROM --platform=linux/amd64 ubuntu:bionic-20220913

RUN apt update

RUN apt -y install make sudo

RUN sudo apt -y install git wget build-essential gcc-aarch64-linux-gnu g++-aarch64-linux-gnu rename
    
RUN mkdir -p /go/src/github.com/confluentinc/cli