FROM --platform=linux/amd64 050879227952.dkr.ecr.us-west-1.amazonaws.com/confluentinc/cli-centos-base-amd64:2.0

COPY . /go/src/github.com/confluentinc/cli/

RUN cd /go/src/github.com/confluentinc/cli && \
    make gorelease-linux-glibc

RUN cd /go/src/github.com/confluentinc/cli && \
    for file in dist/*.txt; do mv -v "$file" "${file/checksums/checksums_linux}"; done;
