FROM --platform=linux/amd64 050879227952.dkr.ecr.us-west-1.amazonaws.com/confluentinc/cli-centos-base-amd64:latest

COPY . /go/src/github.com/confluentinc/cli/

RUN export GO_VERSION=1.20 && \
    wget "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz" && \
    sudo tar -C /usr/local -xzf "go${GO_VERSION}.linux-amd64.tar.gz"

ENV PATH=${PATH}:/usr/local/go/bin:/root/go/bin

RUN go install github.com/goreleaser/goreleaser@v1.16.3-0.20230323115904-f82a32cd3a59

RUN cd /go/src/github.com/confluentinc/cli && \
    make gorelease-linux-glibc

RUN cd /go/src/github.com/confluentinc/cli && \
    for file in dist/*.txt; do mv -v "$file" "${file/checksums/checksums_linux}"; done;
