FROM --platform=linux/arm64/v8 centos-arm64-cli:latest

COPY . /go/src/github.com/confluentinc/cli/

RUN cd /go/src/github.com/confluentinc/cli && \
    make gorelease-linux-glibc-arm64

RUN cd /go/src/github.com/confluentinc/cli && \
    for file in dist/*linux*; do mv -v "$file" "${file/linux/linux}"; done ; \
    for file in dist/*.txt; do mv -v "$file" "${file/checksums/checksums_linux}"; done;
