// Code generated by cli-terraform-generator v0.38.0; DO NOT EDIT.

package budget

import (
	"time"

	"github.com/spf13/cobra"

	budgetv1 "github.com/confluentinc/ccloud-sdk-go-v2/budget/v1"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/config"
	"github.com/confluentinc/cli/v4/pkg/output"
)

type inferenceBudgetCommand struct {
	*pcmd.AuthenticatedCLICommand
}

type inferenceBudgetOut struct {
	ID                  string     `human:"ID" serialized:"id"`
	MaxInferenceUsd     string     `human:"Max Inference Usd" serialized:"max_inference_usd"`
	Period              string     `human:"Period" serialized:"period"`
	PeriodEnd           *time.Time `human:"Period End,omitempty" serialized:"period_end,omitempty"`
	PeriodStart         *time.Time `human:"Period Start,omitempty" serialized:"period_start,omitempty"`
	Scope               string     `human:"Scope" serialized:"scope"`
	EnforcementMode     string     `human:"Enforcement Mode" serialized:"enforcement_mode"`
	AsOf                *time.Time `human:"As Of,omitempty" serialized:"as_of,omitempty"`
	ConsumedUsd         string     `human:"Consumed Usd,omitempty" serialized:"consumed_usd,omitempty"`
	LastNotifiedPercent int32      `human:"Last Notified Percent,omitempty" serialized:"last_notified_percent,omitempty"`
	LastReconciled      *time.Time `human:"Last Reconciled,omitempty" serialized:"last_reconciled,omitempty"`
	PercentConsumed     float64    `human:"Percent Consumed,omitempty" serialized:"percent_consumed,omitempty"`
}

func newInferenceBudgetCommand(cfg *config.Config, prerunner pcmd.PreRunner) *cobra.Command { //nolint:unparam
	cmd := &cobra.Command{
		Use:         "inference-budget",
		Short:       "Manage Confluent Cloud budget inference budgets.",
		Annotations: map[string]string{pcmd.RunRequirement: pcmd.RequireNonAPIKeyCloudLogin},
	}

	c := &inferenceBudgetCommand{
		AuthenticatedCLICommand: pcmd.NewAuthenticatedCLICommand(cmd, prerunner),
	}

	cmd.AddCommand(
		c.newCreateCommand(),
		c.newDeleteCommand(),
		c.newDescribeCommand(),
		c.newListCommand(),
		c.newUpdateCommand(),
		// cli-tfgen:cli-subcommands
	)

	return cmd
}

func printInferenceBudget(cmd *cobra.Command, inferenceBudget budgetv1.BudgetV1InferenceBudget) error {
	table := output.NewTable(cmd)
	out := &inferenceBudgetOut{
		ID:                  inferenceBudget.GetId(),
		MaxInferenceUsd:     inferenceBudget.Spec.GetMaxInferenceUsd(),
		Period:              inferenceBudget.Spec.GetPeriod(),
		PeriodEnd:           inferenceBudget.GetStatus().PeriodEnd,
		PeriodStart:         inferenceBudget.GetStatus().PeriodStart,
		Scope:               inferenceBudget.Spec.GetScope(),
		EnforcementMode:     inferenceBudget.Spec.GetEnforcementMode(),
		AsOf:                inferenceBudget.GetStatus().AsOf,
		ConsumedUsd:         inferenceBudget.Status.GetConsumedUsd(),
		LastNotifiedPercent: inferenceBudget.Status.GetLastNotifiedPercent(),
		LastReconciled:      inferenceBudget.GetStatus().LastReconciled,
		PercentConsumed:     inferenceBudget.Status.GetPercentConsumed(),
	}
	table.Add(out)
	return table.Print()
}

func (c *inferenceBudgetCommand) validArgs(cmd *cobra.Command, args []string) []string {
	if len(args) > 0 {
		return nil
	}

	return c.validArgsMultiple(cmd, args)
}

func (c *inferenceBudgetCommand) validArgsMultiple(cmd *cobra.Command, args []string) []string {
	if err := c.PersistentPreRunE(cmd, args); err != nil {
		return nil
	}

	return c.autocompleteInferenceBudgets()
}

func (c *inferenceBudgetCommand) autocompleteInferenceBudgets() []string {
	inferenceBudgets, err := c.V2Client.ListBudgetInferenceBudgets()
	if err != nil {
		return nil
	}

	suggestions := make([]string, len(inferenceBudgets))
	for i, inferenceBudget := range inferenceBudgets {
		suggestions[i] = inferenceBudget.GetId()
	}
	return suggestions
}
