// Code generated by cli-terraform-generator v0.38.0; DO NOT EDIT.

package budget

import (
	"strings"

	"github.com/spf13/cobra"

	budgetv1 "github.com/confluentinc/ccloud-sdk-go-v2/budget/v1"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
)

func (c *inferenceBudgetCommand) newCreateCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a budget inference budget.",
		Args:  cobra.NoArgs,
		RunE:  c.create,
	}

	// Required flags
	cmd.Flags().String("max-inference-usd", "", "The maximum inference spend permitted within the period, in US dollars as a decimal string with two fractional digits (e.g. \"100.00\"). A string rather than a float so the currency amount is exact.")
	cmd.Flags().String("period", "", "The period over which inference consumption accumulates and resets. The set of values may grow over time.")
	pcmd.RegisterFlagCompletionFunc(cmd, "period", func(_ *cobra.Command, _ []string) []string { return []string{"MONTHLY"} })
	cmd.Flags().String("scope", "", "The scope of resources whose inference consumption counts against this budget. The set of values may grow over time.")
	pcmd.RegisterFlagCompletionFunc(cmd, "scope", func(_ *cobra.Command, _ []string) []string { return []string{"ORGANIZATION"} })
	cobra.CheckErr(cmd.MarkFlagRequired("max-inference-usd"))
	cobra.CheckErr(cmd.MarkFlagRequired("period"))
	cobra.CheckErr(cmd.MarkFlagRequired("scope"))

	// Optional flags
	cmd.Flags().String("enforcement-mode", "", "The action taken when consumption reaches the cap. The set of values may grow over time.")
	pcmd.RegisterFlagCompletionFunc(cmd, "enforcement-mode", func(_ *cobra.Command, _ []string) []string { return []string{"NOTIFY"} })

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *inferenceBudgetCommand) create(cmd *cobra.Command, args []string) error {
	spec := budgetv1.BudgetV1InferenceBudgetSpec{}
	createReq := budgetv1.BudgetV1InferenceBudget{}

	enforcementMode, err := cmd.Flags().GetString("enforcement-mode")
	if err != nil {
		return err
	}
	enforcementMode = strings.ToUpper(enforcementMode)
	if enforcementMode != "" {
		spec.EnforcementMode = budgetv1.PtrString(enforcementMode)
	}

	maxInferenceUsd, err := cmd.Flags().GetString("max-inference-usd")
	if err != nil {
		return err
	}
	spec.MaxInferenceUsd = budgetv1.PtrString(maxInferenceUsd)

	period, err := cmd.Flags().GetString("period")
	if err != nil {
		return err
	}
	period = strings.ToUpper(period)
	spec.Period = budgetv1.PtrString(period)

	scope, err := cmd.Flags().GetString("scope")
	if err != nil {
		return err
	}
	scope = strings.ToUpper(scope)
	spec.Scope = budgetv1.PtrString(scope)

	createReq.Spec = &spec
	inferenceBudget, err := c.V2Client.CreateBudgetInferenceBudget(createReq)
	if err != nil {
		return err
	}

	return printInferenceBudget(cmd, inferenceBudget)
}
