// Code generated by cli-terraform-generator v0.38.0; DO NOT EDIT.

package budget

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/config"
)

func New(cfg *config.Config, prerunner pcmd.PreRunner) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "budget",
		Short: "Manage Confluent Inference Budget.",
	}

	cmd.AddCommand(
		newInferenceBudgetCommand(cfg, prerunner),
		// cli-tfgen:cli-subcommands
	)

	return cmd
}
