// Code generated by cli-terraform-generator v0.26.0; DO NOT EDIT.

package iam

import (
	"strings"

	"github.com/spf13/cobra"

	iamipfilteringv2 "github.com/confluentinc/ccloud-sdk-go-v2/iam-ip-filtering/v2"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
	"github.com/confluentinc/cli/v4/pkg/examples"
	"github.com/confluentinc/cli/v4/pkg/output"
	"github.com/confluentinc/cli/v4/pkg/types"
)

func (c *ipGroupCommand) newUpdateCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "update <id>",
		Short:             "Update an existing IAM IP group.",
		Args:              cobra.ExactArgs(1),
		ValidArgsFunction: pcmd.NewValidArgsFunction(c.validArgs),
		RunE:              c.update,
		Example: examples.BuildExampleString(
			examples.Example{
				Text: `Update the name and add a CIDR block to IP group "ipg-12345":`,
				Code: `confluent iam ip-group update ipg-12345 --name "New Group Name" --add-cidr-blocks 123.234.0.0/16`,
			},
		),
	}

	// Required flags

	// Optional flags
	cmd.Flags().String("name", "", "Updated name of the IP group.")
	cmd.Flags().StringSlice("add-cidr-blocks", nil, "A comma-separated list of CIDR blocks to add.")
	cmd.Flags().StringSlice("remove-cidr-blocks", nil, "A comma-separated list of CIDR blocks to remove.")

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *ipGroupCommand) update(cmd *cobra.Command, args []string) error {
	id := args[0]

	updateReq := iamipfilteringv2.IamV2IpGroup{}

	// Full-object update: the API rejects a partial body, so seed every updatable field from the
	// current object and let the flags below overlay it.
	current, err := c.V2Client.GetIamIpGroup(id)
	if err != nil {
		return err
	}
	updateReq.GroupName = current.GroupName

	if cmd.Flags().Changed("name") {
		groupName, err := cmd.Flags().GetString("name")
		if err != nil {
			return err
		}
		updateReq.GroupName = iamipfilteringv2.PtrString(groupName)
	}

	addCidrBlocks, err := cmd.Flags().GetStringSlice("add-cidr-blocks")
	if err != nil {
		return err
	}
	removeCidrBlocks, err := cmd.Flags().GetStringSlice("remove-cidr-blocks")
	if err != nil {
		return err
	}
	cidrBlocks, warnings := types.AddAndRemove(current.GetCidrBlocks(), addCidrBlocks, removeCidrBlocks)
	for _, warning := range warnings {
		output.ErrPrintf(c.Config.EnableColor, "[WARN] %s\n", warning)
	}
	updateReq.CidrBlocks = &cidrBlocks

	ipGroup, err := c.V2Client.UpdateIamIpGroup(id, updateReq)
	if err != nil {
		if strings.Contains(err.Error(), "lock out") {
			return errors.NewErrorWithSuggestions(err.Error(), "Double check the IP group you are updating. Otherwise, try again from an IP address permitted within this updated IP group or another IP group.")
		}
		return err
	}

	if output.GetFormat(cmd) == output.Human {
		output.Printf(c.Config.EnableColor, "Updated IAM IP group \"%s\".\n", id)
	}
	return printIpGroup(cmd, ipGroup)
}
