// Code generated by cli-terraform-generator v0.22.2; DO NOT EDIT.

package iam

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
)

func (c *certificateAuthorityCommand) newDescribeCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "describe <id>",
		Short:             "Describe an IAM certificate authority.",
		Args:              cobra.ExactArgs(1),
		ValidArgsFunction: pcmd.NewValidArgsFunction(c.validArgs),
		RunE:              c.describe,
	}

	// Required flags

	// Optional flags

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *certificateAuthorityCommand) describe(cmd *cobra.Command, args []string) error {
	id := args[0]
	if !strings.HasPrefix(id, "op-") {
		return fmt.Errorf("failed parsing resource ID: missing prefix \"op-\" is required")
	}

	certificateAuthority, err := c.V2Client.GetIamCertificateAuthority(id)
	if err != nil {
		return err
	}

	return printCertificateAuthority(cmd, certificateAuthority)
}
