// Code generated by cli-terraform-generator v0.12.1; DO NOT EDIT.

package iam

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
)

func (c *userCommand) newDescribeCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "describe <id>",
		Short:             "Describe an IAM user.",
		Args:              cobra.ExactArgs(1),
		ValidArgsFunction: pcmd.NewValidArgsFunction(c.validArgs),
		RunE:              c.describe,
	}

	// Required flags

	// Optional flags

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *userCommand) describe(cmd *cobra.Command, args []string) error {
	id := args[0]
	if !strings.HasPrefix(id, "u-") {
		return fmt.Errorf("failed parsing resource ID: missing prefix \"u-\" is required")
	}

	user, httpResp, err := c.V2Client.GetIamUser(id)
	if err != nil {
		return errors.CatchCCloudV2Error(err, httpResp)
	}

	return printUser(cmd, user)
}
