// Code generated by cli-terraform-generator v0.25.3; DO NOT EDIT.

package iam

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/output"
)

func (c *groupMappingCommand) newListCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List IAM group mappings.",
		Args:  cobra.NoArgs,
		RunE:  c.list,
	}

	// Required flags

	// Optional flags

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *groupMappingCommand) list(cmd *cobra.Command, _ []string) error {
	groupMappings, err := c.V2Client.ListIamGroupMappings()
	if err != nil {
		return err
	}

	list := output.NewList(cmd)
	for _, groupMapping := range groupMappings {
		out := &groupMappingOut{
			ID:          groupMapping.GetId(),
			Name:        groupMapping.GetDisplayName(),
			Description: groupMapping.GetDescription(),
			Filter:      groupMapping.GetFilter(),
			Principal:   groupMapping.GetPrincipal(),
			State:       groupMapping.GetState(),
		}
		list.Add(out)
	}
	return list.Print()
}
