// Code generated by cli-terraform-generator v0.22.2; DO NOT EDIT.

package iam

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/deletion"
	"github.com/confluentinc/cli/v4/pkg/examples"
)

func (c *certificateAuthorityCommand) newDeleteCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "delete <id-1> [id-2] ... [id-n]",
		Short:             "Delete one or more IAM certificate authorities.",
		Args:              cobra.MinimumNArgs(1),
		ValidArgsFunction: pcmd.NewValidArgsFunction(c.validArgsMultiple),
		RunE:              c.delete,
		Example: examples.BuildExampleString(
			examples.Example{
				Text: `Delete certificate authority "op-123456":`,
				Code: "confluent iam certificate-authority delete op-123456",
			},
		),
	}

	// Required flags

	// Optional flags

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddForceFlag(cmd)

	return cmd
}

func (c *certificateAuthorityCommand) delete(cmd *cobra.Command, args []string) error {
	existenceFunc := func(primaryId string) bool {
		_, err := c.V2Client.GetIamCertificateAuthority(primaryId)
		return err == nil
	}

	if err := deletion.ValidateAndConfirm(cmd, args, existenceFunc, "IAM certificate authority"); err != nil {
		return err
	}

	deleteFunc := func(primaryId string) error {
		return c.V2Client.DeleteIamCertificateAuthority(primaryId)
	}

	_, err := deletion.Delete(cmd, args, deleteFunc, "IAM certificate authority")
	return err
}
