// Code generated by cli-terraform-generator v0.26.0; DO NOT EDIT.

package iam

import (
	"github.com/spf13/cobra"

	iamipfilteringv2 "github.com/confluentinc/ccloud-sdk-go-v2/iam-ip-filtering/v2"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/examples"
)

func (c *ipGroupCommand) newCreateCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create <name>",
		Short: "Create an IAM IP group.",
		Args:  cobra.ExactArgs(1),
		RunE:  c.create,
		Example: examples.BuildExampleString(
			examples.Example{
				Text: `Create an IP group named "demo-ip-group" with CIDR blocks "168.150.200.0/24" and "147.150.200.0/24":`,
				Code: "confluent iam ip-group create demo-ip-group --cidr-blocks 168.150.200.0/24,147.150.200.0/24",
			},
		),
	}

	// Required flags
	cmd.Flags().StringSlice("cidr-blocks", nil, "A comma-separated list of CIDR blocks in IP group.")
	cobra.CheckErr(cmd.MarkFlagRequired("cidr-blocks"))

	// Optional flags

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *ipGroupCommand) create(cmd *cobra.Command, args []string) error {
	name := args[0]

	createReq := iamipfilteringv2.IamV2IpGroup{}

	createReq.GroupName = iamipfilteringv2.PtrString(name)
	cidrBlocks, err := cmd.Flags().GetStringSlice("cidr-blocks")
	if err != nil {
		return err
	}
	createReq.CidrBlocks = &cidrBlocks

	ipGroup, err := c.V2Client.CreateIamIpGroup(createReq)
	if err != nil {
		return err
	}

	return printIpGroup(cmd, ipGroup)
}
