// Code generated by cli-terraform-generator v0.16.1; DO NOT EDIT.

package iam

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/deletion"
	"github.com/confluentinc/cli/v4/pkg/examples"
)

func (c *identityProviderCommand) newDeleteCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "delete <id-1> [id-2] ... [id-n]",
		Short:             "Delete one or more IAM identity providers.",
		Args:              cobra.MinimumNArgs(1),
		ValidArgsFunction: pcmd.NewValidArgsFunction(c.validArgsMultiple),
		RunE:              c.delete,
		Example: examples.BuildExampleString(
			examples.Example{
				Text: `Delete identity provider "op-12345":`,
				Code: "confluent iam identity-provider delete op-12345",
			},
		),
	}

	// Required flags

	// Optional flags

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddForceFlag(cmd)

	return cmd
}

func (c *identityProviderCommand) delete(cmd *cobra.Command, args []string) error {
	existenceFunc := func(primaryId string) bool {
		_, err := c.V2Client.GetIamIdentityProvider(primaryId)
		return err == nil
	}

	if err := deletion.ValidateAndConfirm(cmd, args, existenceFunc, "IAM identity provider"); err != nil {
		return err
	}

	deleteFunc := func(primaryId string) error {
		return c.V2Client.DeleteIamIdentityProvider(primaryId)
	}

	_, err := deletion.Delete(cmd, args, deleteFunc, "IAM identity provider")
	return err
}
