// Code generated by cli-terraform-generator v0.22.2; DO NOT EDIT.

package iam

import (
	"github.com/spf13/cobra"

	certificateauthorityv2 "github.com/confluentinc/ccloud-sdk-go-v2/certificate-authority/v2"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/examples"
)

func (c *certificateAuthorityCommand) newCreateCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create <name>",
		Short: "Create an IAM certificate authority.",
		Args:  cobra.ExactArgs(1),
		RunE:  c.create,
		Example: examples.BuildExampleString(
			examples.Example{
				Text: `Create the certificate authority "my-ca" using the certificate chain stored in the "CERTIFICATE_CHAIN" environment variable:`,
				Code: `confluent iam certificate-authority create my-ca --description "my certificate authority" --certificate-chain $CERTIFICATE_CHAIN --certificate-chain-filename certificate.pem`,
			},
			examples.Example{
				Text: "An example of a certificate chain:",
				Code: "-----BEGIN CERTIFICATE-----\nMIIDdTCCAl2gAwIBAgILBAAAAAABFUtaw5QwDQYJKoZIhvcNAQEFBQAwVzELMAkGA1UEBhMCQkUx\nGTAXBgNVBAoTEEdsb2JhbFNpZ24gbnYtc2ExEDAOBgNVBAsTB1Jvb3QgQ0ExGzAZBgNVBAMTEkds\nb2JhbFNpZ24gUm9vdCBDQTAeFw05ODA5MDExMjAwMDBaFw0yODAxMjgxMjAwMDBaMFcxCzAJBgNV\nBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMRAwDgYDVQQLEwdSb290IENBMRswGQYD\nVQQDExJHbG9iYWxTaWduIFJvb3QgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDa\nDuaZjc6j40+Kfvvxi4Mla+pIH/EqsLmVEQS98GPR4mdmzxzdzxtIK+6NiY6arymAZavpxy0Sy6sc\nTHAHoT0KMM0VjU/43dSMUBUc71DuxC73/OlS8pF94G3VNTCOXkNz8kHp1Wrjsok6Vjk4bwY8iGlb\nKk3Fp1S4bInMm/k8yuX9ifUSPJJ4ltbcdG6TRGHRjcdGsnUOhugZitVtbNV4FpWi6cgKOOvyJBNP\nc1STE4U6G7weNLWLBYy5d4ux2x8gkasJU26Qzns3dLlwR5EiUWMWea6xrkEmCMgZK9FGqkjWZCrX\ngzT/LCrBbBlDSgeF59N89iFo7+ryUp9/k5DPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV\nHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRge2YaRQ2XyolQL30EzTSo//z9SzANBgkqhkiG9w0BAQUF\nAAOCAQEA1nPnfE920I2/7LqivjTFKDK1fPxsnCwrvQmeU79rXqoRSLblCKOzyj1hTdNGCbM+w6Dj\nY1Ub8rrvrTnhQ7k4o+YviiY776BQVvnGCv04zcQLcFGUl5gE38NflNUVyRRBnMRddWQVDf9VMOyG\nj/8N7yy5Y0b2qvzfvGn9LhJIZJrglfCm7ymPAbEVtQwdpf5pLGkkeB6zpxxxYu7KyJesF12KwvhH\nhm4qxFYxldBniYUr+WymXUadDKqC5JlR3XC321Y9YeRq4VzW9v493kHMB65jUr9TU/Qr6cf9tveC\nX4XSQRjbgbMEHMUfpIBvFSDJ3gyICh3WZlXi/EjJKSZp4A==\n-----END CERTIFICATE-----",
			},
		),
	}

	// Required flags
	cmd.Flags().String("description", "", "Description of the certificate authority.")
	cmd.Flags().String("certificate-chain-filename", "", "The name of the certificate file.")
	cmd.Flags().String("certificate-chain", "", "The PEM encoded string containing the signing certificate chain used to validate client certs.")
	cobra.CheckErr(cmd.MarkFlagRequired("certificate-chain"))
	cobra.CheckErr(cmd.MarkFlagRequired("certificate-chain-filename"))
	cobra.CheckErr(cmd.MarkFlagRequired("description"))

	// Optional flags
	cmd.Flags().String("crl-url", "", "The URL from which to fetch the CRL (Certificate Revocation List) for the certificate authority.")
	cmd.Flags().Bool("require-crl-on-client-certificate", false, "Require CRL validation on client certificates.")
	cmd.Flags().String("crl-chain", "", "The PEM encoded string containing the CRL for this certificate authority. Defaults to this over `crl_url` if available.")

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *certificateAuthorityCommand) create(cmd *cobra.Command, args []string) error {
	name := args[0]

	createReq := certificateauthorityv2.IamV2CreateCertRequest{}

	createReq.DisplayName = certificateauthorityv2.PtrString(name)
	description, err := cmd.Flags().GetString("description")
	if err != nil {
		return err
	}
	createReq.Description = certificateauthorityv2.PtrString(description)

	certificateChainFilename, err := cmd.Flags().GetString("certificate-chain-filename")
	if err != nil {
		return err
	}
	createReq.CertificateChainFilename = certificateauthorityv2.PtrString(certificateChainFilename)

	crlUrl, err := cmd.Flags().GetString("crl-url")
	if err != nil {
		return err
	}
	if crlUrl != "" {
		createReq.CrlUrl = certificateauthorityv2.PtrString(crlUrl)
	}

	requireCrlOnClientCertificate, err := cmd.Flags().GetBool("require-crl-on-client-certificate")
	if err != nil {
		return err
	}
	if requireCrlOnClientCertificate {
		createReq.RequireCrlOnClientCertificate = certificateauthorityv2.PtrBool(requireCrlOnClientCertificate)
	}

	certificateChain, err := cmd.Flags().GetString("certificate-chain")
	if err != nil {
		return err
	}
	createReq.CertificateChain = certificateauthorityv2.PtrString(certificateChain)

	crlChain, err := cmd.Flags().GetString("crl-chain")
	if err != nil {
		return err
	}
	if crlChain != "" {
		createReq.CrlChain = certificateauthorityv2.PtrString(crlChain)
	}

	certificateAuthority, err := c.V2Client.CreateIamCertificateAuthority(createReq)
	if err != nil {
		return err
	}

	return printCertificateAuthority(cmd, certificateAuthority)
}
