// Code generated by cli-terraform-generator v0.25.3; DO NOT EDIT.

package iam

import (
	"fmt"

	"github.com/spf13/cobra"

	ssov2 "github.com/confluentinc/ccloud-sdk-go-v2/sso/v2"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/config"
	"github.com/confluentinc/cli/v4/pkg/output"
)

type groupMappingCommand struct {
	*pcmd.AuthenticatedCLICommand
}

type groupMappingOut struct {
	ID          string `human:"ID" serialized:"id"`
	Name        string `human:"Name" serialized:"name"`
	Description string `human:"Description" serialized:"description"`
	Filter      string `human:"Filter" serialized:"filter"`
	Principal   string `human:"Principal" serialized:"principal"`
	State       string `human:"State" serialized:"state"`
}

func newGroupMappingCommand(cfg *config.Config, prerunner pcmd.PreRunner) *cobra.Command { //nolint:unparam
	cmd := &cobra.Command{
		Use:         "group-mapping",
		Short:       "Manage Confluent Cloud IAM group mappings.",
		Annotations: map[string]string{pcmd.RunRequirement: pcmd.RequireCloudLogin},
	}

	c := &groupMappingCommand{
		AuthenticatedCLICommand: pcmd.NewAuthenticatedCLICommand(cmd, prerunner),
	}

	cmd.AddCommand(
		c.newCreateCommand(),
		c.newDeleteCommand(),
		c.newDescribeCommand(),
		c.newListCommand(),
		c.newUpdateCommand(),
		// cli-tfgen:cli-subcommands
	)

	return cmd
}

func printGroupMapping(cmd *cobra.Command, groupMapping ssov2.IamV2SsoGroupMapping) error {
	table := output.NewTable(cmd)
	out := &groupMappingOut{
		ID:          groupMapping.GetId(),
		Name:        groupMapping.GetDisplayName(),
		Description: groupMapping.GetDescription(),
		Filter:      groupMapping.GetFilter(),
		Principal:   groupMapping.GetPrincipal(),
		State:       groupMapping.GetState(),
	}
	table.Add(out)
	return table.Print()
}

func (c *groupMappingCommand) validArgs(cmd *cobra.Command, args []string) []string {
	if len(args) > 0 {
		return nil
	}

	return c.validArgsMultiple(cmd, args)
}

func (c *groupMappingCommand) validArgsMultiple(cmd *cobra.Command, args []string) []string {
	if err := c.PersistentPreRunE(cmd, args); err != nil {
		return nil
	}

	return c.autocompleteGroupMappings()
}

func (c *groupMappingCommand) autocompleteGroupMappings() []string {
	groupMappings, err := c.V2Client.ListIamGroupMappings()
	if err != nil {
		return nil
	}

	suggestions := make([]string, len(groupMappings))
	for i, groupMapping := range groupMappings {
		suggestions[i] = fmt.Sprintf("%s\t%s", groupMapping.GetId(), groupMapping.GetDisplayName())
		if description := groupMapping.GetDescription(); description != "" {
			suggestions[i] += ": " + description
		}
	}
	return suggestions
}
