// Code generated by cli-terraform-generator v0.25.3; DO NOT EDIT.

package iam

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
)

func (c *groupMappingCommand) newDescribeCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "describe <id>",
		Short:             "Describe an IAM group mapping.",
		Args:              cobra.ExactArgs(1),
		ValidArgsFunction: pcmd.NewValidArgsFunction(c.validArgs),
		RunE:              c.describe,
	}

	// Required flags

	// Optional flags

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *groupMappingCommand) describe(cmd *cobra.Command, args []string) error {
	id := args[0]
	if !strings.HasPrefix(id, "group-") {
		return fmt.Errorf("failed parsing resource ID: missing prefix \"group-\" is required")
	}

	groupMapping, err := c.V2Client.GetIamGroupMapping(id)
	if err != nil {
		return err
	}

	return printGroupMapping(cmd, groupMapping)
}
