// Code generated by cli-terraform-generator v0.22.2; DO NOT EDIT.

package iam

import (
	"fmt"
	"time"

	"github.com/spf13/cobra"

	certificateauthorityv2 "github.com/confluentinc/ccloud-sdk-go-v2/certificate-authority/v2"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/config"
	"github.com/confluentinc/cli/v4/pkg/output"
)

type certificateAuthorityCommand struct {
	*pcmd.AuthenticatedCLICommand
}

type certificateAuthorityOut struct {
	ID                            string      `human:"ID" serialized:"id"`
	Name                          string      `human:"Name" serialized:"name"`
	Description                   string      `human:"Description" serialized:"description"`
	CertificateChainFilename      string      `human:"Certificate Chain Filename" serialized:"certificate_chain_filename"`
	CrlUrl                        string      `human:"CRL URL,omitempty" serialized:"crl_url,omitempty"`
	RequireCrlOnClientCertificate bool        `human:"Require CRL On Client Certificate" serialized:"require_crl_on_client_certificate"`
	Fingerprints                  []string    `human:"Fingerprints" serialized:"fingerprints"`
	ExpirationDates               []time.Time `human:"Expiration Dates" serialized:"expiration_dates"`
	SerialNumbers                 []string    `human:"Serial Numbers" serialized:"serial_numbers"`
	CrlSource                     string      `human:"CRL Source,omitempty" serialized:"crl_source,omitempty"`
	CrlUpdatedAt                  *time.Time  `human:"CRL Updated At,omitempty" serialized:"crl_updated_at,omitempty"`
}

func newCertificateAuthorityCommand(cfg *config.Config, prerunner pcmd.PreRunner) *cobra.Command { //nolint:unparam
	cmd := &cobra.Command{
		Use:         "certificate-authority",
		Short:       "Manage Confluent Cloud IAM certificate authorities.",
		Annotations: map[string]string{pcmd.RunRequirement: pcmd.RequireCloudLogin},
	}

	c := &certificateAuthorityCommand{
		AuthenticatedCLICommand: pcmd.NewAuthenticatedCLICommand(cmd, prerunner),
	}

	cmd.AddCommand(
		c.newCreateCommand(),
		c.newDeleteCommand(),
		c.newDescribeCommand(),
		c.newListCommand(),
		c.newUpdateCommand(),
		// cli-tfgen:cli-subcommands
	)

	return cmd
}

func printCertificateAuthority(cmd *cobra.Command, certificateAuthority certificateauthorityv2.IamV2CertificateAuthority) error {
	table := output.NewTable(cmd)
	out := &certificateAuthorityOut{
		ID:                            certificateAuthority.GetId(),
		Name:                          certificateAuthority.GetDisplayName(),
		Description:                   certificateAuthority.GetDescription(),
		CertificateChainFilename:      certificateAuthority.GetCertificateChainFilename(),
		CrlUrl:                        certificateAuthority.GetCrlUrl(),
		RequireCrlOnClientCertificate: certificateAuthority.GetRequireCrlOnClientCertificate(),
		Fingerprints:                  certificateAuthority.GetFingerprints(),
		ExpirationDates:               certificateAuthority.GetExpirationDates(),
		SerialNumbers:                 certificateAuthority.GetSerialNumbers(),
		CrlSource:                     certificateAuthority.GetCrlSource(),
		CrlUpdatedAt:                  certificateAuthority.CrlUpdatedAt,
	}
	table.Add(out)
	return table.Print()
}

func (c *certificateAuthorityCommand) validArgs(cmd *cobra.Command, args []string) []string {
	if len(args) > 0 {
		return nil
	}

	return c.validArgsMultiple(cmd, args)
}

func (c *certificateAuthorityCommand) validArgsMultiple(cmd *cobra.Command, args []string) []string {
	if err := c.PersistentPreRunE(cmd, args); err != nil {
		return nil
	}

	return c.autocompleteCertificateAuthorities()
}

func (c *certificateAuthorityCommand) autocompleteCertificateAuthorities() []string {
	certificateAuthorities, err := c.V2Client.ListIamCertificateAuthorities()
	if err != nil {
		return nil
	}

	suggestions := make([]string, len(certificateAuthorities))
	for i, certificateAuthority := range certificateAuthorities {
		suggestions[i] = fmt.Sprintf("%s\t%s", certificateAuthority.GetId(), certificateAuthority.GetDisplayName())
		if description := certificateAuthority.GetDescription(); description != "" {
			suggestions[i] += ": " + description
		}
	}
	return suggestions
}
