// Code generated by cli-terraform-generator v0.16.1; DO NOT EDIT.

package iam

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/output"
)

func (c *identityProviderCommand) newListCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List IAM identity providers.",
		Args:  cobra.NoArgs,
		RunE:  c.list,
	}

	// Required flags

	// Optional flags

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *identityProviderCommand) list(cmd *cobra.Command, _ []string) error {
	identityProviders, err := c.V2Client.ListIamIdentityProviders()
	if err != nil {
		return err
	}

	list := output.NewList(cmd)
	for _, identityProvider := range identityProviders {
		out := &identityProviderOut{
			ID:            identityProvider.GetId(),
			Name:          identityProvider.GetDisplayName(),
			Description:   identityProvider.GetDescription(),
			IssuerUri:     identityProvider.GetIssuer(),
			JwksUri:       identityProvider.GetJwksUri(),
			IdentityClaim: identityProvider.GetIdentityClaim(),
		}
		list.Add(out)
	}
	return list.Print()
}
