// Code generated by cli-terraform-generator v0.22.1; DO NOT EDIT.

package iam

import (
	"github.com/spf13/cobra"

	iamv2 "github.com/confluentinc/ccloud-sdk-go-v2/iam/v2"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/examples"
)

func (c *serviceAccountCommand) newCreateCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create <name>",
		Short: "Create an IAM service account.",
		Args:  cobra.ExactArgs(1),
		RunE:  c.create,
		Example: examples.BuildExampleString(
			examples.Example{
				Text: `Create a service account named "my-service-account".`,
				Code: `confluent iam service-account create my-service-account --description "new description"`,
			},
		),
	}

	// Required flags

	// Optional flags
	pcmd.AddResourceOwnerFlag(cmd, c.AuthenticatedCLICommand)
	cmd.Flags().String("description", "", "A free-form description of the Service Account.")

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *serviceAccountCommand) create(cmd *cobra.Command, args []string) error {
	name := args[0]
	assignedResourceOwner, err := cmd.Flags().GetString("resource-owner")
	if err != nil {
		return err
	}

	createReq := iamv2.IamV2ServiceAccount{}

	createReq.DisplayName = iamv2.PtrString(name)
	description, err := cmd.Flags().GetString("description")
	if err != nil {
		return err
	}
	if description != "" {
		createReq.Description = iamv2.PtrString(description)
	}

	serviceAccount, err := c.V2Client.CreateIamServiceAccount(assignedResourceOwner, createReq)
	if err != nil {
		return err
	}

	return c.printServiceAccount(cmd, serviceAccount)
}
