// Code generated by cli-terraform-generator; DO NOT EDIT.

package rtce

import (
	"fmt"
	"strings"
	"time"

	"github.com/spf13/cobra"

	rtcev1 "github.com/confluentinc/ccloud-sdk-go-v2/rtce/v1"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/errors"
	"github.com/confluentinc/cli/v4/pkg/kafka"
	"github.com/confluentinc/cli/v4/pkg/wait"
)

func (c *rtceTopicCommand) newCreateCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create an RTCE topic.",
		Args:  cobra.NoArgs,
		RunE:  c.create,
	}

	// Required flags
	pcmd.AddCloudAwsFlag(cmd)
	cmd.Flags().String("description", "", "A model-readable description of the RTCE topic.")
	cmd.Flags().String("region", "", "The cloud region where the RTCE topic is deployed.")
	cmd.Flags().String("topic-name", "", "The Kafka topic name containing the data for the RTCE topic.")
	cobra.CheckErr(cmd.MarkFlagRequired("cloud"))
	cobra.CheckErr(cmd.MarkFlagRequired("description"))
	cobra.CheckErr(cmd.MarkFlagRequired("region"))
	cobra.CheckErr(cmd.MarkFlagRequired("topic-name"))

	// Optional flags
	pcmd.AddEnvironmentFlag(cmd, c.AuthenticatedCLICommand)
	pcmd.AddClusterFlag(cmd, c.AuthenticatedCLICommand)
	cmd.Flags().Bool("wait", false, "Wait for the RTCE topic to reach a ready or failed state before returning.")
	cmd.Flags().Duration("timeout", time.Hour, "Maximum time to wait for the RTCE topic to reach a ready or failed state when --wait is set (e.g., '30s', '5m', '1h30m').")

	pcmd.AddContextFlag(cmd, c.CLICommand)
	pcmd.AddOutputFlag(cmd)

	return cmd
}

func (c *rtceTopicCommand) create(cmd *cobra.Command, args []string) error {
	spec := rtcev1.RtceV1RtceTopicSpec{}
	createReq := rtcev1.RtceV1RtceTopic{}

	cloud, err := cmd.Flags().GetString("cloud")
	if err != nil {
		return err
	}
	cloud = strings.ToUpper(cloud)
	spec.Cloud = rtcev1.PtrString(cloud)

	description, err := cmd.Flags().GetString("description")
	if err != nil {
		return err
	}
	spec.Description = rtcev1.PtrString(description)

	environmentId, err := c.Context.EnvironmentId()
	if err != nil {
		return err
	}
	spec.Environment = &rtcev1.EnvScopedObjectReference{Id: environmentId}

	kafkaClusterConfig, err := kafka.GetClusterForCommand(c.V2Client, c.Context)
	if err != nil {
		return err
	}
	kafkaClusterId := kafkaClusterConfig.GetId()
	spec.KafkaCluster = &rtcev1.EnvScopedObjectReference{Id: kafkaClusterId}

	region, err := cmd.Flags().GetString("region")
	if err != nil {
		return err
	}
	spec.Region = rtcev1.PtrString(region)

	topicName, err := cmd.Flags().GetString("topic-name")
	if err != nil {
		return err
	}
	spec.TopicName = rtcev1.PtrString(topicName)

	createReq.Spec = &spec
	rtceTopic, httpResp, err := c.V2Client.CreateRtceTopic(createReq)
	if err != nil {
		return errors.CatchCCloudV2Error(err, httpResp)
	}

	shouldWait, err := cmd.Flags().GetBool("wait")
	if err != nil {
		return err
	}
	if shouldWait {
		timeout, err := cmd.Flags().GetDuration("timeout")
		if err != nil {
			return err
		}
		// Re-fetch the resource via its describe endpoint until it leaves the
		// pending set. The lookup key matches the describe command's positional
		// arg — an id, topic_name, display_name, etc. (see PrimaryIdentifierGetter).
		waitKey := rtceTopic.Spec.GetTopicName()
		rtceTopic, err = wait.PollPhases(cmd.Context(), wait.PhaseOptions[rtcev1.RtceV1RtceTopic]{
			Fetch: func() (rtcev1.RtceV1RtceTopic, error) {
				v, _, err := c.V2Client.GetRtceTopic(waitKey, environmentId, kafkaClusterId)
				return v, err
			},
			Phase:         func(v rtcev1.RtceV1RtceTopic) string { return v.Status.GetPhase() },
			PendingPhases: []string{"PENDING", "PROVISIONING"},
			FailedPhases:  []string{"FAILED", "UNAVAILABLE"},
			Delay:         5 * time.Second,
			PollInterval:  10 * time.Second,
			Timeout:       timeout,
		})
		if err != nil {
			// wait.ErrFailed / wait.ErrTimeout are package-level sentinels
			// returned directly from Poll, so == is the correct compare.
			switch err {
			case wait.ErrFailed:
				return errors.NewErrorWithSuggestions(
					fmt.Sprintf(`RTCE topic "%s" entered failed phase %q`, waitKey, rtceTopic.Status.GetPhase()),
					fmt.Sprintf("Inspect the RTCE topic with `confluent rtce rtce-topic describe %s`.", waitKey),
				)
			case wait.ErrTimeout:
				return errors.NewErrorWithSuggestions(
					fmt.Sprintf(`wait timed out: RTCE topic "%s" is still in phase %q`, waitKey, rtceTopic.Status.GetPhase()),
					"Increase `--timeout` or omit `--wait`.",
				)
			default:
				return err
			}
		}
	}

	return printRtceTopic(cmd, rtceTopic)
}
