// Code generated by cli-terraform-generator; DO NOT EDIT.

package endpoint

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/config"
)

func New(cfg *config.Config, prerunner pcmd.PreRunner) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "endpoint",
		Short: "Manage Endpoint.",
	}

	cmd.AddCommand(
		newEndpointCommand(cfg, prerunner),
		// cli-tfgen:cli-subcommands
	)

	return cmd
}
