// Code generated by cli-terraform-generator; DO NOT EDIT.

package endpoint

import (
	"github.com/spf13/cobra"

	pcmd "github.com/confluentinc/cli/v4/pkg/cmd"
	"github.com/confluentinc/cli/v4/pkg/config"
)

type endpointCommand struct {
	*pcmd.AuthenticatedCLICommand
}

type endpointOut struct {
	Cloud          string `human:"Cloud" serialized:"cloud"`
	Region         string `human:"Region" serialized:"region"`
	Service        string `human:"Service" serialized:"service"`
	IsPrivate      bool   `human:"Is Private" serialized:"is_private"`
	ConnectionType string `human:"Connection Type" serialized:"connection_type"`
	Endpoint       string `human:"Endpoint" serialized:"endpoint"`
	EndpointType   string `human:"Endpoint Type" serialized:"endpoint_type"`
	Environment    string `human:"Environment" serialized:"environment"`
	Resource       string `human:"Resource" serialized:"resource"`
	Gateway        string `human:"Gateway" serialized:"gateway"`
	AccessPoint    string `human:"Access Point" serialized:"access_point"`
}

func newEndpointCommand(cfg *config.Config, prerunner pcmd.PreRunner) *cobra.Command { //nolint:unparam
	cmd := &cobra.Command{
		Use:         "endpoint",
		Short:       "Manage endpoints.",
		Annotations: map[string]string{pcmd.RunRequirement: pcmd.RequireNonAPIKeyCloudLogin},
	}

	c := &endpointCommand{
		AuthenticatedCLICommand: pcmd.NewAuthenticatedCLICommand(cmd, prerunner),
	}

	cmd.AddCommand(
		c.newListCommand(),
	)

	return cmd
}
